sprucelabsai/workspace.sprucebot-skills-kit

- packages/react-sprucebot/src/skillskit/next/_document.js
- packages/sprucebot-skills-kit/interface/__mocks__/styleMock.js
- packages/sprucebot-skills-kit/jest.config.js
- packages/sprucebot-skills-kit/package.json
- yarn.lock
* Adds mock for styles to allow jest to run
* Moves `swagger-jsdoc` to a dependency
* Fixes 404ing next stylesheet which is no longer needed w/ next 7 for styles to be loaded
> A Few Fixes

- packages/sprucebot-skills-kit/config/default.js
> fix: remove duplicate in config

- packages/sprucebot-skills-kit/jest/enzymeSetup.js
> Mock global logger

- .vscode/settings.json
- packages/sprucebot-skills-kit/.env.example
- packages/sprucebot-skills-kit/server/server.js
> fix: swagger doc should generate after sprucebot-skills-kit-server initalized

- packages/sprucebot-skills-kit/server/models/Organization.js
> Remove broken association for Organization model

- packages/sprucebot-skills-kit-server/package.json
- packages/sprucebot-skills-kit/interface/pages/_app.js
- packages/sprucebot-skills-kit/package.json
- yarn.lock
> Upgrade logger for better browser compatibility

- packages/heartwood-components/components/09-bigcalendar/bigcalendar.scss
- packages/heartwood-components/public/stylesheets/global.css
- packages/react-heartwood-components/src/components/BigCalendar/components/Header/Header.js
- packages/react-heartwood-components/src/components/BigCalendar/components/HeaderControls/HeaderControls.js
- packages/react-heartwood-components/src/components/Forms/components/DatePicker/DatePicker.js
✨ styling of mobile controls
⚡️add `initialVisibleMonth` prop to `DatePicker~ component
> mobile menu stlying

- packages/react-heartwood-components/src/components/BigCalendar/components/DragGrid/DragGrid.js
- packages/react-heartwood-components/src/components/BigCalendar/components/Views/Day.js
- yarn.lock
[SB-1391](https://sprucelabsai.atlassian.net/browse/SB-1391)
Clicking on processing time for an appointment passes the click to the view so you can create an appointment or drag the calendar.
> fix: SB-1391

- packages/react-heartwood-components/src/index.js
Export the form layout components so they can be used in skills.
> fix: export the form layout components

- packages/heartwood-components/components/02-forms/phone-input.scss
- packages/heartwood-components/components/03-structure/04-page-components/01-page/page.config.js
- packages/heartwood-components/components/03-structure/04-page-components/01-page/page.hbs
- packages/heartwood-components/components/03-structure/page.scss
- packages/heartwood-components/components/09-bigcalendar/bigcalendar.scss
- packages/heartwood-components/stylesheets/heartwood-components.scss
- packages/heartwood-components/stylesheets/vendor/react-phone-number-input/_style.scss
- packages/react-heartwood-components/src/components/Forms/components/PhoneInput/PhoneInput.js
- packages/react-heartwood-components/src/components/Page/Page.js
update the react-phone-input styles to match heartwood.
> Phone Input style updates

- packages/heartwood-components/components/09-bigcalendar/event-details.scss
- packages/react-heartwood-components/src/components/BigCalendar/BigCalendar.js
✨[SBL-1568](https://sprucelabsai.atlassian.net/browse/SBL-1568) hide event title overflow
✨[SBL-1495](https://sprucelabsai.atlassian.net/browse/SBL-1495) update `headerCellDowFormat`
> Small Fixes

- packages/react-heartwood-components/src/components/Text/Text-story.js
- packages/react-heartwood-components/src/components/Text/Text.js
[DES-226](https://sprucelabsai.atlassian.net/browse/DES-226)
Updates the `<Text />` and `<Span/>` components to:
- Have a configurable `element` with fallback to `p` and `span` respectively
- Passes `..rest` props to the rendered element (for things like href, target, etc…)
> Update <Text />

- packages/react-heartwood-components/src/components/Forms/components/FormLayout/FormLayout.js
- packages/react-heartwood-components/src/components/Forms/components/FormLayout/components/FormLayoutItem/FormLayoutItem.js
- packages/react-heartwood-components/src/components/Forms/components/PhoneInput/PhoneInput.js
- packages/react-heartwood-components/src/components/Forms/index.js
- packages/react-heartwood-components/src/components/Page/components/PageHeader/PageHeader.js
- packages/react-heartwood-components/src/components/Pagination/Pagination.js
- packages/react-heartwood-components/src/components/Table/Table.js
- packages/react-heartwood-components/src/index.js
2. phone number error rendering
3. phone number only support US (will need prop to accept countries)
4. phone number formatting and validation exported
5. page header class->className fix
6. exporting pagination props type (was assumed to be the case in another file)
7. table row clicking
> 1. pass through of props on FormLayout & FormLayoutItem

- packages/react-heartwood-components/src/components/Table/Table.js
Adds a callback to selectable tables
> Tables onSelection callback

- packages/heartwood-components/components/07-navigation/tabs.scss
- packages/react-heartwood-components/src/components/Page/components/PageHeader/PageHeader.js
- packages/react-heartwood-components/src/components/Tabs/Tabs.js
Corrects the layout for tabs in page header.
- [ *] Bug
> Page Header Corrections

- packages/heartwood-components/components/99-web/header-primary.scss
- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/HeaderPrimary-story.js
- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/HeaderPrimary.js
- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/components/LocationMenu/LocationMenu.js
- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/components/UserMenu/UserMenu.js
[SBL-1606](https://sprucelabsai.atlassian.net/browse/SBL-1606)
Adds buttons to the primary header to link into skill and location management.
- [ •] Feature
> Update <HeaderPrimary />

- packages/spruce-skill-server/middleware/auth.js
- packages/spruce-skill/config/default.js
> Attach locationId, organizationId, and jwt to authV2

- packages/spruce-skill-server/middleware/auth.js
- packages/spruce-skill/server/events/get-views.js
* Fixes async function calls not working properly in v2 events
> fix: await next() in auth middleware

- packages/spruce-skill-server/package.json
- yarn.lock
> package fix - graphql-tag (skill-server)

- packages/react-heartwood-components/src/components/Card/components/OnboardingCard.js
- packages/react-heartwood-components/src/components/Tabs/Tabs.js
- packages/react-heartwood-components/src/index.js
> exporting types

- packages/eslint-plugin-spruce/index.js
- Targeting gql-tagged templates is more consistent; the trick is getting rules in place to make people tag their template literals. There's still ways around it that I'm not catching, like assigning via a ternary.
> fix(eslint): Tweaking logic around interpolation linting

- packages/spruce-skill-server/gql/router.js
> variables passed to gql

- packages/react-heartwood-components/src/components/Table/Table.js
Can set initially selected ids on the table.
> initialselectedids

- packages/eslint-config-spruce/index.js
- packages/eslint-config-spruce/package.json
- yarn.lock
> fix(eslint): Include babel-eslint

- packages/react-heartwood-components/package.json
- packages/react-heartwood-components/src/components/FontLoader/FontLoader.js
> fix(fontloader): Repair deps, remove reference to storybook in component

- packages/react-heartwood-components/src/components/ImageCropper/ImageCropper.js
- packages/react-heartwood-components/src/index.js
⚡️Export `<ImageCropper>` component
⚡️Add `onSubmit` prop and handler
⚡️Save `sliderValue` to state so it is honored with use of the `onChange` applied to `<Slider>`
> Export <ImageCropper> component

- packages/spruce-utils/lib/errors.js
- packages/spruce-utils/lib/graphql.js
- Also fix stack traces for FE logs, and split on newlines for easier 
parsing.
> feat(graphql): Improve logging data and messaging

- packages/heartwood-components/components/10-text/text.scss
- packages/react-heartwood-components/src/components/Icon/Icon.js
- yarn.lock
Style icons inside of `<Text>` components
> Style icons used in text component and text links

- packages/heartwood-components/components/99-web/header-primary.scss
> Primary Header Fix

- packages/spruce-skill-server/lib/GraphQLSubscriptionServer.js
- packages/spruce-skill-server/package.json
- yarn.lock
> Fix missing ioredis dependency

- packages/heartwood-components/components/__partials/icon.hbs
- packages/heartwood-components/components/empty-state/empty-state.config.js
- packages/heartwood-components/components/empty-state/empty-state.hbs
- packages/heartwood-components/components/empty-state/empty-state.scss
- packages/heartwood-components/stylesheets/heartwood-components.scss
Creates a re-usable Empty State Heartwood Component with headline, subheadline, icon, and button action.
* [SBL-1977](https://sprucelabsai.atlassian.net/browse/SBL-1977)
Screenshot review then code review to make sure the design expectations have been met.
n/a
No
> [SBL-1977] Empty State Heartwood Component

- packages/heartwood-components/components/06-modal/modal.scss
- packages/react-heartwood-components/src/components/Modal/Modal.js
- packages/react-heartwood-components/src/components/Modal/components/ModalBody/ModalBody.js
- packages/react-heartwood-components/src/components/Modal/components/ModalHeader/ModalHeader.js
- packages/react-heartwood-components/src/components/PagedModal/PagedModal-story.js
- packages/react-heartwood-components/src/components/PagedModal/PagedModal.js
- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
- packages/react-heartwood-components/src/index.js
Create a Paged Modal component that allows paging through multi-stepped modals.
> Paged Modal

- packages/react-heartwood-components/src/components/Toast/Toast.js
- packages/spruce-skill/interface/pages/skill-views/example.js
- packages/spruce-skill/package.json
See https://github.com/sprucelabsai/ai-spruce-web/pull/144
> feat(spruce-skill): Add example of requesting that Core show a toast

- packages/react-heartwood-components/src/components/RecordTable/RecordTable.js
[SBL-2094](https://sprucelabsai.atlassian.net/browse/SBL-2094)
Implements a `Data not available` Empty State for failed API fetches, a `No matches` for when the filter/search returns no results, otherwise falls back to whatever the empty state props are that were passed in.
> minor(RecordTable): RecordTable EmptyState instance for failed API fetches [SBL-2094]

- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
Add optional prop to `<RecordSelectionList>` to hide "# select" text
> optional prop to hide count text in <RecordSelectList>

- packages/heartwood-components/public/icons/ic_guests_large.svg
- packages/heartwood-components/public/icons/ic_team_large.svg
Add large icons for guest and team
> Add large guest and team icons

- packages/heartwood-components/components/99-web/sidebar.scss
- packages/heartwood-components/stylesheets/core/_layout.scss
- Add lte() utility for media queries
> feat(responsive): Don't let mobile styles for sidebars leak to desktop

- docs/spruce-skill/messages.md
[SBL-2220](https://sprucelabsai.atlassian.net/browse/SBL-2220)
Added documentation for Push Notifications
> Added documentation for Push Notifications

- packages/react-sprucebot/lib/components/Calendar/BigCalendar.js
- packages/react-sprucebot/lib/components/DateSelect/DateSelect.js
- packages/react-sprucebot/lib/components/ImageCropper/ImageCropper.js
- packages/react-sprucebot/lib/skillskit/index.js
- packages/react-sprucebot/lib/skillskit/next/Page.js
- packages/react-sprucebot/lib/skillskit/next/_app.js
- packages/react-sprucebot/lib/skillskit/next/_document.js
- packages/react-sprucebot/src/components/Calendar/BigCalendar.js
- packages/react-sprucebot/src/components/DateSelect/DateSelect.js
- packages/react-sprucebot/src/components/FormField/FormField.js
- packages/react-sprucebot/src/components/ImageCropper/ImageCropper.js
- yarn.lock
[SBL-2122](https://sprucelabsai.atlassian.net/browse/SBL-2122)
Adds the ability to deselect dates on the DateSelect component.
> v7 Hotfix: Allow deselecting date on DateSelect

- packages/react-sprucebot/package.json
- packages/sprucebot-node/package.json
- packages/sprucebot-skills-kit-server/package.json
- packages/sprucebot-skills-kit/package.json
> fix: manually bump package versions to fix ci build

- packages/react-heartwood-components/src/components/Card/Card-story.js
- packages/react-heartwood-components/src/components/Card/components/CardBuilder.js
Had to move the object that maps GQL types to components inside the render function because I DON'T KNOW.
Fixed card-store to use the update components correctly
> fixes to restore card builder

- packages/spruce-skill-server/index.js
- packages/spruce-skill-server/tests/v1APIMocks.js
> Fix skill without devDependencies installed crashing on boot

- packages/spruce-skill-server/tests/SpruceTest.js
> Pass before options into beforeBase

- packages/spruce-skill-server/tests/mocks/SandboxMock.js
- packages/spruce-skill-server/tests/v1APIMocks.js
> fix: debug not defined

- packages/spruce-next-helpers/src/skillskit/index.js
See: https://github.com/sprucelabsai/ai-spruce-web/pull/218
> feat(modal): Handle onClosed event broadcast by core

- packages/react-heartwood-components/src/components/ContextMenu/ContextMenu.js
* Fixes context menu passing back incorrect payload to callback method
- [SDEV3-1321](https://sprucelabsai.atlassian.net/browse/SDEV3-1321)
* Need to merge this PR before updating booking `react-heartwood-components` package
> [SDEV3-1321] fix context menu payloads

- packages/react-heartwood-components/src/components/BigCalendar/components/DragGrid/DragGrid.js
* Fixes an error preventing events from being dropped on mobile
- [SDEV3-1330](https://sprucelabsai.atlassian.net/browse/SDEV3-1330)
Need to update booking to the latest version of `react-heartwood-components` once this PR is merged
> [SDEV3-1330] fixes error on drop event on mobile

- packages/react-heartwood-components/src/components/Button/Button.js
- packages/react-heartwood-components/src/components/Forms/components/Checkbox/Checkbox.js
- packages/react-heartwood-components/src/components/Page/Page.js
> fix(Page): Page should accept a spread of remaining props

- packages/heartwood-components/components/10-text/text.scss
- packages/react-heartwood-components/src/components/TextStyle/TextStyle-story.js
- packages/react-heartwood-components/src/components/TextStyle/TextStyle.js
* Adds `subdued` option for `TextStyle` component
- [SDEV3-584](https://sprucelabsai.atlassian.net/browse/SDEV3-584)
> Add subdued text style

- packages/spruce-next-helpers/src/skillskit/index.js
- packages/spruce-skill/interface/pages/skill-views/dashboard_location/index.js
- packages/spruce-skill/interface/pages/skill-views/example.js
Skills need alerts too
- [SDEV3-1612](https://sprucelabsai.atlassian.net/browse/SDEV3-1612)
NA
NA
> [SDEV3-1612] alerts in skills

- packages/heartwood-components/components/10-text/text.scss
- packages/react-heartwood-components/src/components/Text/Text-story.js
- packages/react-heartwood-components/src/components/Text/Text.js
Adds ability to pass text templating syntax to Text component to enable rich formatting and interactions within text component
- [SDEV3-1593](https://sprucelabsai.atlassian.net/browse/SDEV3-1593)
> [SDEV3-1593] Adds basic text templating to Text component

- packages/spruce-next-helpers/src/skillskit/index.js
- packages/spruce-skill/interface/pages/skill-views/dashboard_location/index.js
Adds convenience methods for modifying button props on confirm modals
- [SDEV3-934](https://sprucelabsai.atlassian.net/browse/SDEV3-934)
> [SDEV3-934]: Add convenience methods for modifying button props

- packages/heartwood-components/components/08-lists/lists.scss
- packages/heartwood-components/stylesheets/base/_base.scss
Hides focus on iframes and `RecordSelectionList`s.
- [SDEV3-1589](https://sprucelabsai.atlassian.net/browse/SDEV3-1589)
No
> [SDEV3-1589] Hide focus on iframes

- packages/heartwood-components/components/02-forms/checkbox.scss
- packages/react-heartwood-components/src/components/Forms/Forms-story.js
Adds the correct styles to disabled checkboxes and radios
- [SDEV3-1598](https://sprucelabsai.atlassian.net/browse/SDEV3-1598)
no
> [SDEV3-1598] React Heartwood: Checkbox and Radio components do not have disabled states

- packages/heartwood-components/components/02-forms/autosuggest.scss
- packages/heartwood-components/components/08-lists/lists.scss
- packages/react-heartwood-components/src/components/ContextMenu/ContextMenu.js
- packages/react-heartwood-components/src/components/Forms/Forms-story.js
- packages/react-heartwood-components/src/components/Forms/components/Autosuggest/Autosuggest.js
- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectList-story.js
- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
- Fixes Context Menu from being clipped
- [SDEV3-1662](https://sprucelabsai.atlassian.net/browse/SDEV3-1662)
> [SDEV3-1662] Fix Context menu from being clipped

- packages/react-heartwood-components/src/components/BigCalendar/components/Views/Day.js
Fixed bug in BigCalendar: "Drag adjusting an appointment booked within an the processing time of another pre-existing appointment causes the pre-existing to become inactive"
- [SDEV3-1637](https://sprucelabsai.atlassian.net/browse/SDEV3-1637)
No
> [SDEV-1637] Fixed: Booking - drag adjusting an appointment bug

- packages/react-heartwood-components/src/components/Forms/components/Autosuggest/Autosuggest.js
Fixes <AutoSuggest> results positioning in Safari
- [SDEV3-1748](https://sprucelabsai.atlassian.net/browse/SDEV3-1748)
> [SDEV3-1748] Fix autosuggest positioning in Safari

- packages/heartwood-components/components/08-lists/lists.scss
- packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.js
- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectList-story.js
- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
- packages/react-heartwood-components/src/utilities.js
* Updates RecordSelectionList to use ListItem vs custom RecordSelectionListItem to simplify rendering data and expose all ListItem capabilities while remaining backwards compatible for existing implementations.
* Adds basic utility method to check for deprecated props and warn developers
- [SDEV3-1950](https://sprucelabsai.atlassian.net/browse/SDEV3-1950)
> [SDEV3-1950]Brandon/feat/record select list

- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectList-story.js
- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
- Needed to match new comps for group creation
- [SDEV3-1814](https://sprucelabsai.atlassian.net/browse/SDEV3-1814)
> feat(RSL): Add label to search field [SDEV3-1814]

- packages/react-sprucebot/lib/skillskit/next/Page.js
- packages/react-sprucebot/src/skillskit/next/Page.js
Fixes scrolling and clipping for legacy skill views in new web while remaining backwards compatible for legacy web.
- [SDEV3-1847](https://sprucelabsai.atlassian.net/browse/SDEV3-1847)
`react-sprucebot` will need to be updated in all legacy skills
Depends on https://github.com/sprucelabsai/ai-spruce-web/pull/253
> [SDEV3-1847] Fix scroll/clipping in heartwood legacy views

- packages/heartwood-components/components/06-modal/modal.scss
- packages/react-heartwood-components/src/components/Modal/components/ModalBody/ModalBody.js
- [SDEV3-1814](https://sprucelabsai.atlassian.net/browse/SDEV3-1814)
> feat(ModalBody): Allow full bleed modal contents [SDEV3-1814]

- packages/heartwood-components/components/03-structure/page.scss
- packages/react-heartwood-components/src/components/Page/components/PageHeader/PageHeader.js
> fix(PageHeader): Fix element alignment of primaryAction CTA

- packages/heartwood-components/components/03-structure/page.scss
- packages/react-heartwood-components/src/components/Page/Page-story.js
- packages/react-heartwood-components/src/components/Page/components/PageHeader/PageHeader.js
- Add a new story to represent what happens when the Page is within a flexible layout (like in Core)
- Tested in core separately
> fix(PageHeader): Fix collapsible header when page is in flexible layout

- packages/react-heartwood-components/src/components/Avatar/Avatar.tsx
- packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.tsx
- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.tsx
> chore(typescript): Convert ListItem and RecordSelectionList to TSX

- packages/heartwood-components/components/08-lists/lists.scss
- packages/react-heartwood-components/.storybook/data/lists.js
- packages/react-heartwood-components/src/components/Button/Button.tsx
- packages/react-heartwood-components/src/components/List/List-story.js
- packages/react-heartwood-components/src/components/List/List-story.tsx
- packages/react-heartwood-components/src/components/List/List.tsx
- packages/react-heartwood-components/src/components/List/components/ExpandableListItem/ExpandableListItem.tsx
- packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.tsx
- packages/react-heartwood-components/src/components/List/components/SortableList/SortableList.tsx
- packages/react-heartwood-components/src/components/List/index.js
- packages/react-heartwood-components/src/components/List/index.tsx
- packages/react-heartwood-components/src/index.tsx
Adds styling for nested lists and the ability to expand/collapse list items that have them.
- [x ] Feature
- [SDEV3-2099](https://sprucelabsai.atlassian.net/browse/SDEV3-2099)
- [SDEV3-2048](https://sprucelabsai.atlassian.net/browse/SDEV3-2048)
No
Oh Sprucebot, my feelings are far too complex to be described by a gif.
> [SDEV3-2099] Heartwood Lists Updates

- packages/react-heartwood-components/src/index.tsx
This was an oversight in a previous PR; patching this and merging as soon as it passes tests.
> hotfix(List): Repair export of List component

- packages/heartwood-components/components/10-text/text.scss
- [SDEV3-1814](https://sprucelabsai.atlassian.net/browse/SDEV3-1814)
> fix(Heading): Use bolder font [SDEV3-1814]

- packages/react-heartwood-components/src/index.tsx
Export TruncatedList from react-heartwood-components
> fix: export TruncatedList

- packages/spruce-node/index.js
- packages/spruce-node/mock/apiSchema.json
- packages/spruce-node/mock/index.js
- packages/spruce-skill-server/index.js
- packages/spruce-skill-server/tests/apiMocks.js
- packages/spruce-skill/config/default.js
* Implements skill sync against new gql endpoint: https://github.com/sprucelabsai/com-sprucebot-api/pull/521
* Sets s3 bucket via api response
* Set up mutation/query mock responses
- [SDEV3-643](https://sprucelabsai.atlassian.net/browse/SDEV3-643)
> [SDEV3-643] Set s3 bucket via api

- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/HeaderPrimary-story.js
- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/HeaderPrimary.js
> Update login button href to go to the login page

- packages/heartwood-components/components/08-lists/lists.scss
- packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.tsx
* Fixes styling of selectable lists with avatar
- [SDEV3-1970](https://sprucelabsai.atlassian.net/browse/SDEV3-1970)
> [SDEV3-1970] fix: correctly style selectable people list with avatar

- packages/react-heartwood-components/src/components/View/View.tsx
Add TS types for `privacyLink` and `termsLink`
> fix: add ts types to View privacyLink and termsLink

- packages/react-heartwood-components/src/components/Forms/components/PhoneInput/PhoneInput.js
- Replaces existing `isValidPhoneNumber` w/ a custom, less restrictive 
version that only accepts US/CAN numbers
> fix(PhoneInput): Add simple phone validator

- packages/spruce-utils/lib/iframes.js
Brings in support for legacy skill views
- [SDEV3-2176](https://sprucelabsai.atlassian.net/browse/SDEV3-2176)
NA
NA
> [SDEV3-2176] legacy iframe messaging support

- packages/heartwood-components/components/99-web/main-content.scss
- packages/react-heartwood-components/src/components/View/View-story.js
- packages/react-heartwood-components/src/components/View/View.tsx
- Fix was just to revert flex prop, but added stories to 
illustrate/validate the fix.
- Improved older View stories to make sure they show scrolling content
> fix(View): Address regression in main content scrolling

- packages/spruce-skill/config/default.js
- packages/spruce-skill/server/events/big-search.js
- packages/spruce-skill/server/events/import-from-big-search.js
- packages/spruce-skill/server/types.js
Brings in big search examples
- [SDEV3-378](https://sprucelabsai.atlassian.net/browse/SDEV3-378)
NA
NA
NA
> [SDEV-378] - spruce-skill has big search examples

- packages/spruce-skill/server/events/big-search.js
Fixes a slice issue
- [SDEV3-368](https://sprucelabsai.atlassian.net/browse/SDEV3-378)
NA
NA
NA
> [SDEV3-378] slice fix

- packages/react-heartwood-components/src/components/Forms/components/PhoneInput/PhoneInput.tsx
- This component's underlying lib works well in its current 
internal-state format (and less well otherwise). We need a refactor / 
replacement component, but in the meantime I'm wiring in support for a 
defaultValue.
- Also migrate to TSX
> fix(PhoneInput): Allow defaultValue w/ internal state

- packages/react-heartwood-components/src/components/TruncatedList/TruncatedList.tsx
Adds `reset()` method to TruncatedList component
> refactor: convert TruncatedList to TS and add reset method

- packages/react-heartwood-components/src/components/TruncatedList/TruncatedList.tsx
Fixes error when TruncatedList attempts to reset non-existent RecordSelectionList
> fix(TruncatedList): check if recordSelectionListRef exists before reset

- packages/react-heartwood-components/src/components/Card/index.tsx
- packages/react-heartwood-components/src/components/Forms/components/FormBuilder/FormBuilder-story.js
- packages/react-heartwood-components/src/components/Forms/components/FormBuilder/FormBuilder.js
- packages/react-heartwood-components/src/components/Forms/components/FormBuilder/components/FormInner/FormInner.js
- packages/react-heartwood-components/src/index.tsx
> Fix <Card /> exports

- packages/spruce-skill/config/default.js
- packages/spruce-skill/server/events/did-update-user.js
renames the `did-update-profile` to `did-update-user` so it matches what is in core.
- [SDEV3-2270](https://sprucelabsai.atlassian.net/browse/SDEV3-2270)
NA
NA
> [SDEV-2270] - event was named wrong

- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/HeaderPrimary.js
It don't do. It removes a TODO
- [SDEV3-1987](https://sprucelabsai.atlassian.net/browse/SDEV3-1987)
> [SDEV3-1987] remove todo from HeaderPrimary component

- packages/react-sprucebot/lib/components/Dialog/Dialog.js
- packages/react-sprucebot/lib/skillskit/index.js
- packages/react-sprucebot/src/components/Dialog/Dialog.js
- packages/react-sprucebot/src/skillskit/index.js
brings scroll and dialog placement for skills in new web. (major change around iframe scroll vs window scroll)
- [SDEV3-2277](https://sprucelabsai.atlassian.net/browse/SDEV3-2277)
NA
NA
NA
> [SDEV3-2277] legacy scroll support

- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/HeaderPrimary.js
Hides big search if no callback is set
- [SDEV3-2280](https://sprucelabsai.atlassian.net/browse/SDEV3-2280)
NA
NA
> [SDEV3-2280] only show search if a callback is set

- packages/heartwood-components/components/03-structure/page.scss
Makes skill views usable in ai-web on mobile safari
- [SDEV3-2289](https://sprucelabsai.atlassian.net/browse/SDEV3-2289)
NA
NA
NA
> [SDEV3-2289] - style tweak for ios

- packages/heartwood-components/components/03-structure/page.scss
- packages/spruce-utils/lib/graphql.js
stop gap for mobile ios iframe scrolling
> Mobile ios style change

- packages/spruce-skill-server/package.json
- packages/spruce-skill/package.json
- yarn.lock
> Update logger version

- packages/react-heartwood-components/.storybook/addons.js
- packages/react-heartwood-components/.storybook/config.js
- packages/react-heartwood-components/.storybook/webpack.config.js
- packages/react-heartwood-components/package.json
- packages/react-heartwood-components/src/components/Avatar/Avatar-story.js
- packages/react-heartwood-components/src/components/Button/Button-story.js
- packages/react-heartwood-components/src/components/Card/Card-story.js
- packages/react-heartwood-components/src/components/Card/index.tsx
- packages/react-heartwood-components/src/components/EmptyState/EmptyState-story.tsx
- packages/react-heartwood-components/src/components/List/List-story.tsx
- packages/react-heartwood-components/src/components/Message/Message-story.js
- packages/react-heartwood-components/src/components/TruncatedList/TruncatedList-story.js
- yarn.lock
Upgrades to storybook 5 and some way cool addons
> storybook 5

- packages/react-heartwood-components/src/index.tsx
Exports IIconProps so we can use it in BigCalendar
NA
NA
NA
NA
> Icon export

- packages/heartwood-components/components/03-structure/table.scss
Fix alignment of table cells.
- [SDEV3-2329](https://sprucelabsai.atlassian.net/browse/SDEV3-2329)
> [SDEV3-2329] fix: table cell alignment

- packages/heartwood-components/components/03-structure/table.scss
Reverts sprucelabsai/workspace.sprucebot-skills-kit#616
> Revert "[SDEV3-2329] fix: table cell alignment"

- packages/spruce-skill-server/lib/SpruceModel.ts
- packages/spruce-skill-server/models/Location.ts
- packages/spruce-skill-server/models/Organization.ts
- packages/spruce-skill-server/models/Skill.ts
- packages/spruce-skill-server/models/User.ts
- packages/spruce-skill-server/models/UserLocation.ts
- packages/spruce-skill-server/models/UserOrganization.ts
Sets core model `paranoid` flag based on FDW settings
> [SDEV3-2361] Fix "paranoid" setting on core models

- packages/spruce-skill-server/gql/Schema.ts
> less noisy logging

- packages/spruce-skill-server/gql/Schema.ts
- packages/spruce-skill-server/tests/lib/HttpsMock.ts
- packages/spruce-skill/config/auth.ts
Ensures types instances are preservered as schemas are extended.
> fix: type preservation

- packages/spruce-skill-server/gql/Schema.ts
- packages/spruce-skill-server/interfaces/global.ts
Fixes how gql is built to handle SDL and longhand definitions
> [SDEV-2361] Schema building fix

- packages/react-heartwood-components/src/components/BotText/BotText.tsx
- packages/react-heartwood-components/src/components/Button/Button.tsx
- packages/react-heartwood-components/src/components/Card/Card.tsx
- packages/react-heartwood-components/src/components/Card/components/CardBody.tsx
- packages/react-heartwood-components/src/components/EmptyState/EmptyState-story.tsx
- packages/react-heartwood-components/src/components/EventDetails/components/EventDetailsItem/EventDetailsItem.tsx
- packages/react-heartwood-components/src/components/Forms/components/Autosuggest/Autosuggest.tsx
- packages/react-heartwood-components/src/components/Icon/Icon.tsx
- packages/react-heartwood-components/src/components/List/List-story.tsx
- packages/react-heartwood-components/src/components/List/components/ExpandableListItem/ExpandableListItem.tsx
- packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.tsx
- packages/react-heartwood-components/src/components/List/components/SortableList/SortableList.tsx
- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.tsx
- packages/react-heartwood-components/src/components/RecordTable/RecordTable-story.tsx
- packages/react-heartwood-components/src/components/RecordTable/RecordTable.tsx
- packages/react-heartwood-components/src/components/SplitButton/SplitButton.tsx
- packages/react-heartwood-components/src/components/Table/Table.tsx
- packages/react-heartwood-components/src/components/Text/Text-story.tsx
- packages/react-heartwood-components/src/components/Text/Text.tsx
- packages/react-heartwood-components/src/components/Toast/Toast-story.tsx
- packages/react-heartwood-components/src/components/Toast/components/ToastWrapper/ToastWrapper.tsx
- packages/react-heartwood-components/tsconfig.json
- important to have compatibility w/ GQL types
> fix(TS): Fix types to be strict-compliant [SDEV3-531]

- .circleci/config.yml
- packages/react-heartwood-components/src/components/Button/Button.tsx
- packages/react-heartwood-components/src/components/List/List.tsx
- packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.tsx
- packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.tsx
- packages/react-heartwood-components/src/components/SplitButton/SplitButton.tsx
- packages/spruce-types/src/generated/api-gql.ts
- packages/spruce-types/src/generated/hw-gql.ts
- packages/spruce-types/src/gql/Button.gql
Makes minor changes so components can work through GQL, also updates Interfaces for action executor respelling.
- [SDEV3-2474](https://sprucelabsai.atlassian.net/browse/SDEV3-2474)
NA
NA
NA
> [SDEV3-2474] event details

- packages/spruce-skill/.vscode/settings.json
> VSCode setting to do auto-imports using relative paths

- packages/spruce-utils/lib/graphql.ts
- packages/spruce-utils/package.json
- yarn.lock
Just a prepwork PR for adding GQL subscription helpers here
- [SDEV3-509](https://sprucelabsai.atlassian.net/browse/SDEV3-509)
> fix(GQL): Convert gql util client to TS [SDEV3-509]

- packages/spruce-utils/lib/graphql.ts
- Also clean up types
- [SDEV3-509](https://sprucelabsai.atlassian.net/browse/SDEV3-509)
> feat(GraphQL): Add `subscription` helper to the gql client [SDEV3-509]

- packages/spruce-next-helpers/src/skillskit/index.ts
- packages/spruce-utils/lib/graphql.ts
Changes the signature for updating a calendar event to handle changing of event id.
NA
NA
NA
> updateEvent signature

- packages/spruce-skill-server/models/Organization.ts
Make sure slug is available on org.
NA
NA
NA
NA
> make slug on org available in skills

- packages/spruce-skill-server/models/Location.ts
- packages/spruce-skill-server/models/Organization.ts
Adds slugs other places it was missing.
> missed slugs

- packages/spruce-next-helpers/package.json
- packages/spruce-next-helpers/src/index.ts
- packages/spruce-next-helpers/src/skillskit/helpers/errors.ts
Easier to get at friendlyReason
> parse friendly reason from SpruceWebError

- packages/spruce-next-helpers/src/skillskit/helpers/errors.ts
> explicitly typed

- packages/spruce-next-helpers/src/skillskit/next/PageWrapper.js
lets you switch between v1 and v2 views
> handle both jwt v1 and v2

- packages/spruce-node/index.ts
Strongly types event emitting options as well as add more comments for help
- [SDEV3-2586](https://sprucelabsai.atlassian.net/browse/SDEV3-2586)
NA
NA
NA
> [SDEV3-2586] strongly typed emit options

- packages/spruce-next-helpers/src/skillskit/index.ts
Updates the BigSearch api and lets us avoid using the LEGACY SearchForUser message
> update big search api

- packages/spruce-types/src/generated/hw-gql.ts
- packages/spruce-types/src/gql/types/ActionExecutor.gql
- [SDEV3-2362](https://sprucelabsai.atlassian.net/browse/SDEV3-2362)
> [SDEV3-2362] Add "slug" to ActionCoreRedirectPayload

- packages/spruce-types/src/generated/hw-gql.ts
- packages/spruce-types/src/gql/types/ActionExecutor.gql
- [SDEV3-2362](https://sprucelabsai.atlassian.net/browse/SDEV3-2362)
> [SDEV3-2362] Fix slug added to wrong redirect payload

- packages/spruce-types/src/gql/queries/CalendarEvents.ts
- [SDEV3-2362](https://sprucelabsai.atlassian.net/browse/SDEV3-2362)
> [SDEV3-2362] Update shared query w/ new params

- packages/spruce-types/src/gql/queries/Cards.ts
> [SDEV3-2362] another query update

- packages/spruce-types/src/generated/hw-gql.ts
- packages/spruce-types/src/gql/types/ActionExecutor.gql
Adds some callbacks for pass, cancel, and fail scenarios.
> onComplete, onCancel, onFail on actions

- packages/spruce-types/src/gql/types/ActionExecutor.gql
> remove on onFail

- .vscode/launch.json
- packages/spruce-skill-server/tests/GQLMethodTests.ts
- packages/spruce-skill/config/default.ts
Fixes running a single test from vscode launch menu
> Fix single file test

- packages/spruce-types/src/generated/hw-gql.ts
- packages/spruce-types/src/gql/types/ActionExecutor.gql
> actionResponse

- packages/react-heartwood-components/src/components/Forms/components/FormBuilder/FormBuilder.js
- packages/spruce-next-helpers/package.json
- packages/spruce-next-helpers/src/skillskit/helpers/errors.ts
filter non-unique messages and hide form builder button
> filter non-unique messages and hide form builder button

- packages/spruce-next-helpers/src/skillskit/next/PageWrapper.js
- packages/spruce-skill-server/controllers/auth.ts
- Actually tested this time, misread the API; working as expected with `sameSite` header.
> fix(Cookies): options on set, not constructor [SDEV3-2622]

- packages/react-heartwood-components/src/components/Card/components/CardBody.tsx
- packages/react-heartwood-components/src/components/Card/components/CardSection.tsx
makes the full bleed on card section optional
> full-bleed

- packages/spruce-skill/interface/pages/_app.js
> check for initialProps

- packages/heartwood-components/components/03-structure/card.scss
Changes margin top to padding-top because margin-top had no effect.
> margin to padding

- packages/react-heartwood-components/src/components/Card/components/CardBuilder.tsx
Pass onAction function to the renderer for CardBuilder items
- [SDEV3-457](https://sprucelabsai.atlassian.net/browse/SDEV3-457)
> Pass onAction to rendered item

- packages/react-heartwood-components/package.json
- packages/spruce-next-helpers/package.json
- packages/spruce-next-helpers/src/skillskit/next/PageWrapper.js
- packages/spruce-skill-server/controllers/auth.js
- packages/spruce-skill-server/package.json
- yarn.lock
- [SDEV3-2622](https://sprucelabsai.atlassian.net/browse/SDEV3-2622)
> fix(npm-Cookies): v8.x: Update to version supporting sameSite [SDEV3-2622]

- packages/react-heartwood-components/package.json
- yarn.lock
updates phone number version to address missing files
> phone update

- .circleci/config.yml
Uses a circleci image that has node 10 instead of 12
> Fix builds - update CircleCI build image

- packages/spruce-skill-server/gql/resolvers/UIEnhancements/queries/getUIEnhancements.ts
- packages/spruce-skill-server/gql/resolvers/typeResolvers.ts
* Adds missing resolvers for core types
* Moves resolvers to own file instead of being dependent on UI Enhancements being enabled.
> Fix missing resolvers needed for UIEnhancements

- packages/react-heartwood-components/src/components/Card/components/CardBuilder.tsx
- packages/react-heartwood-components/src/components/Card/components/CardHeader.tsx
- packages/react-heartwood-components/src/components/Toast/Toast.tsx
We need to pass onAction to the CardHeader for actions in the header.
- [SDEV3-490](https://sprucelabsai.atlassian.net/browse/SDEV3-490)
> Pass onAction to CardHeader

- packages/heartwood-components/components/03-structure/page.scss
- Behold, hilarious amount of testing effort for a single-line change
- [SDEV3-2754](https://sprucelabsai.atlassian.net/browse/SDEV3-2754)
> fix(Page): 100% height for where Page used w/o container [SDEV3-2754]

- packages/react-heartwood-components/src/components/View/View-story.js
- packages/react-heartwood-components/src/components/View/View.tsx
- [SDEV3-2788](https://sprucelabsai.atlassian.net/browse/SDEV3-2788)
> feat(View): Add isChromeless prop to disable view chrome [SDEV3-2788]

- packages/heartwood-components/components/08-lists/lists.scss
- packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.tsx
- [SDEV3-2758](https://sprucelabsai.atlassian.net/browse/SDEV3-2758)
> fix(Lists): Spacing for list item sections, avatars [SDEV3-2758]

- packages/react-heartwood-components/src/components/Tabs/Tabs.tsx
Stops list of services from bleeding up when "Add Service" is clicked to launch booking from core
> [SDEV3-2803] services list issue

- .circleci/config.yml
- .vscode/settings.json
- package.json
- packages/react-sprucebot/lib/components/Calendar/BigCalendar.js
- packages/react-sprucebot/lib/components/DateSelect/DateSelect.js
- packages/react-sprucebot/lib/components/ImageCropper/ImageCropper.js
- packages/react-sprucebot/lib/skillskit/next/_app.js
- packages/react-sprucebot/lib/skillskit/next/_document.js
- packages/react-sprucebot/src/components/DateSelect/DateSelect.js
Fixes bug where calendar wouldn't always update the available days because it was using a cached function. Passing a new function on each render as suggested in this issue: `https://github.com/airbnb/react-dates/issues/847` fixes it.
- [SDEV3-2857](https://sprucelabsai.atlassian.net/browse/SDEV3-2857)
> [SDEV3-2857] (v7 react-sprucebot) Fix DateSelect not refreshing available days

- packages/spruce-skill-server/index.ts
* Detects if API returns 404 for event type generator and logs an "info" instead of a full error. This will help prevent confusion where this version of skills kit is used against an older version of API
* Better error message on skill sync if API is unreachable
> Better skill startup error messaging

- packages/spruce-types/src/gql/queries/UIEnhancements.ts
Needed to fix proper showing of ui enhancements in context menus within skill view
- [SDEV3-2896](https://sprucelabsai.atlassian.net/browse/SDEV3-2896)
> [SDEV3-2896] getUIEnhancements query should return contextMenuItems

- packages/spruce-skill/.vscode/settings.json
> Fix vscode settings for latest eslint plugin

- packages/react-heartwood-components/src/components/Tabs/Tabs.tsx
Check for tabGroup ref before acting on it
Slightly extend timeout before initial measurement
> Prevent tabs error

- packages/react-sprucebot/lib/components/DateSelect/DateSelect.js
Needed to rebuild to get updated component
> [SDEV3-3041] Add updated lib component

- packages/spruce-utils/lib/graphql.ts
- Needed so that ai-web can respond to disconnect/reconnect on the socket
- [SDEV3-3050](https://sprucelabsai.atlassian.net/browse/SDEV3-3050)
> feat(GQLClient): Allow tapping into wsLink callbacks

- .vscode/settings.json
- packages/spruce-skill-server/gql/types/Metadata.ts
- packages/spruce-skill-server/index.ts
- packages/spruce-skill-server/interfaces/models.ts
- packages/spruce-skill-server/models/Metadata.ts
- yarn.lock
* Defines `Metadata` as a core model
* Fix eslint settings
* Fix missing semantic-release package
- [SDEV3-2988](https://sprucelabsai.atlassian.net/browse/SDEV3-2988)
> [SDEV3-2988] Move Metadata definition to spruce-skill-server

- .vscode/settings.json
- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/HeaderPrimary.js
- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/components/UserMenu/UserMenu.js
- yarn.lock
Fixes issue where certain tappable area near avatar would result in user menu immediately closing
- [SDEV3-3054](https://sprucelabsai.atlassian.net/browse/SDEV3-3054)
> [SDEV3-3054] fix user menu toggle

- packages/spruce-utils/lib/graphql.ts
- Previous feature-add did not address teardown and re-init of listeners (which in my partial defense isn't clear at all in the docs...)
- Less in my defense, I accidentally called `onReconnected` where I meant to call `onDisconnected`, resulting in double listeners. 
- These two things combined led to exponential growth in listeners every time the socket reconnected, eventually crashing the browser
Before:
After:
- [SDEV3-3060](https://sprucelabsai.atlassian.net/browse/SDEV3-3060)
> fix(GraphQL): Destroy and re-init listeners on resubscribe [SDEV3-3060]

- packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/HeaderPrimary.js
Detect click into iframe so that user menu closes if open
> [SDEV3-3054] user menu fix for iframes

- packages/react-heartwood-components/src/components/Button/Button.tsx
- packages/react-heartwood-components/src/components/Card/Card-story.tsx
- packages/react-heartwood-components/src/components/Card/components/CardBuilder.tsx
- packages/react-heartwood-components/src/components/EventDetails/eventDetailsMock.ts
- packages/spruce-types/src/generated/hw-gql.ts
- packages/spruce-types/src/gql/types/Button.gql
Just merging the v9 fixes in #819 into v10.
> v9->v10 for CardBuilder fixes

- packages/spruce-next-helpers/src/skillskit/next/_document.js
- yarn.lock
- Also check in unversioned yarn changes
- [SDEV3-3094](https://sprucelabsai.atlassian.net/browse/SDEV3-3094)
> feat(SkillsKit): Only allow whitelabel stylesheets on guest pages [SDEV3-3094]

- packages/react-heartwood-components/src/components/Card/components/CardBuilder.tsx
- packages/react-heartwood-components/src/index.tsx
- A few minor issues to resolve to integrate ai-web fully with canonical CardBuilder GQL type
> fix(CardBuilder): Expose proper types, add null type

- packages/react-sprucebot/lib/skillskit/next/Page.js
- packages/react-sprucebot/src/skillskit/next/Page.js
- Fix falsey comparisons that were creating bad edges.
> fix(Whitelabel): Fix previous solution (v7)

- packages/react-heartwood-components/src/components/Layout/Layout-story.tsx
- packages/react-heartwood-components/src/components/Layout/components/LayoutSpacing/LayoutSpacing.tsx
- packages/spruce-types/src/generated/hw-gql.ts
- packages/spruce-types/src/gql/types/Layout.gql
> feat(Layout): Add spacing component

- packages/react-heartwood-components/src/components/Layout/Layout.tsx
- packages/react-heartwood-components/src/components/Layout/components/LayoutSection/LayoutSection.tsx
- packages/react-heartwood-components/src/components/Layout/components/LayoutSpacing/LayoutSpacing.tsx
- packages/react-heartwood-components/src/components/LayoutBuilder/LayoutBuilder-story.tsx
- packages/react-heartwood-components/src/components/LayoutBuilder/LayoutBuilder.tsx
- packages/spruce-types/src/generated/hw-gql.ts
- packages/spruce-types/src/gql/types/Layout.gql
- packages/spruce-types/src/gql/types/LayoutBuilder.gql
Merge after https://github.com/sprucelabsai/workspace.sprucebot-skills-kit/pull/843
> feat(LayoutBuilder): Integrate Layout component

- packages/react-heartwood-components/src/components/LayoutBuilder/LayoutBuilder-story.tsx
- packages/react-heartwood-components/src/components/LayoutBuilder/LayoutBuilder.tsx
- packages/react-heartwood-components/src/components/Page/Page.tsx
- packages/spruce-types/src/generated/hw-gql.ts
- packages/spruce-types/src/gql/types/LayoutBuilder.gql
- packages/spruce-types/src/gql/types/Page.gql
Now possible with `LayoutBuilder`:
> feat(Page): Add Page to LayoutBuilder

- packages/spruce-types/package.json
- packages/spruce-utils/package.json
> Allow node versions greater than 10
