packages/react-sprucebot/src/components/Forms/components/Slider/Slider.js
Add controlled mode for sliders. Without this, the slider is still movable, even if the value being passed into properties does not change.
=> feat: Add controlled mode for slider component

packages/react-sprucebot/lib/Sprucebot.js, packages/react-sprucebot/lib/skillskit/next/_app.js, packages/react-sprucebot/lib/skillskit/next/_document.js, packages/react-sprucebot/src/Sprucebot.js, packages/react-sprucebot/src/skillskit/next/_app.js, packages/react-sprucebot/src/skillskit/next/_document.js
NextJS introduced `_app.js` for persistent layout that modifies with the page, and as a part of that started erroring if you included <title> tags in _document.js.
```
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
```
This is a noop for skills since they all run in iframes, but fixes the error and opens the door for us to use _app.js in the future.
=> fix: Implement NextJS _app.js, remove title from _document.js

packages/spruce-next-helpers/src/skillskit/next/_app.js, packages/spruce-next-helpers/src/skillskit/next/_document.js
This was accidentally merged into dev, redoing it for the folder rename hoola.
=> fix: Add _app.js, nix title in _document bug from Next7 migration

packages/react-heartwood-components/.storybook/data/actions.js, packages/react-heartwood-components/src/components/BigCalendar/EventDetails-story.js, packages/react-heartwood-components/src/components/BigCalendar/components/EventBlock/EventBlock.js, packages/react-heartwood-components/src/components/BigCalendar/components/EventDetails/components/EventDetailsHeader/EventDetailsHeader.js, packages/react-heartwood-components/src/components/BigCalendar/storyEvents.js, packages/react-heartwood-components/src/components/Button/Button-story.js, packages/react-heartwood-components/src/components/Button/Button.js, packages/react-heartwood-components/src/components/Card/Card-story.js, packages/react-heartwood-components/src/components/Card/components/CardHeader.js, packages/react-heartwood-components/src/components/ContextMenu/ContextMenu.js, packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/components/UserMenu/UserMenu.js, packages/react-heartwood-components/src/components/Core/components/Sidebar/components/SidebarExpander/SidebarExpander.js, packages/react-heartwood-components/src/components/Forms/components/Autosuggest/Autosuggest.js, packages/react-heartwood-components/src/components/Forms/components/Tag/Tag.js, packages/react-heartwood-components/src/components/Icon/Icon.js, packages/react-heartwood-components/src/components/ImageCropper/ImageCropper.js, packages/react-heartwood-components/src/components/List/List-story.js, packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.js, packages/react-heartwood-components/src/components/Modal/components/ModalHeader/ModalHeader.js, packages/react-heartwood-components/src/components/Pagination/Pagination.js, packages/react-heartwood-components/src/components/Toast/Toast.js
[SBL-1139](https://sprucelabsai.atlassian.net/browse/SBL-1139)
This is a request from @liquidg3 to switch Heartwood to specifying icons by configuration, rather than injecting custom `Icon` components or specifying custom icons w/ heartwood classes.
Most instances of Icons are still "custom," as you can see below, but the SVG imported is passed as a reference instead of as a component (see `customIcon` references below).
This is obviously a large change since `Button` and `List` are widely used, and both passthrough to `Icon`. Please advise if you have any concerns with external projects that have imported any affected component.
=> Switch most instances of icon injection to configuration pattern

packages/react-heartwood-components/src/components/BigCalendar/components/HeaderControls/HeaderControls.js
Fixes regression and allows clicking outside of datepicker to close
=> fix regression on SBL-1171 - datepicker not closing on clicking outside

packages/react-heartwood-components/src/components/Core/components/HeaderPrimary/HeaderPrimary.js, packages/react-heartwood-components/src/components/View/View.js
When implementing `View` this started throwing warnings, since the required props weren't being passed through.
I'm additionally removing the search-bar if those props aren't provided; I'd imagine we might want to use this view in a logged-in context without search.
=> Allow View and HeaderPrimary to set necessary search props

packages/heartwood-components/components/02-forms/select.scss, packages/heartwood-components/stylesheets/core/_colors.scss
Updates the styling of `select`s that are `disabled` or `readonly`. Also includes an update to `$c-primary` colors to match the latest Heartwood designs.
=> Minor Styling Fixes

packages/react-heartwood-components/src/components/Icon/Icon.js
- Just don't render it, and console warn.
- I was initially okay with throwing, but a user might get an icon from 
the API and not be the responsible party for it not being in the icon 
list.
- In that case, we should just render nothing.
- We might want to have an error handling hook so the user can determine 
what to do if no icon is found, something to consider for later.
=> fix(icons): Don't die if the icon can't be found

packages/react-heartwood-components/src/components/Button/Button.js, packages/react-heartwood-components/src/components/Tabs/components/Tab/Tab.js, packages/react-heartwood-components/src/components/_utilities/Anchor.js
- This is a bit of a proto for how I want to handle anchor rendering 
generally in react-heartwood; I often want to control anchor rendering 
so that I can instrument client side routing with `next/link`, etc.
=> feature(tabs): Defer rendering of anchors to downstream code

packages/heartwood-components/components/07-navigation/01-tabs/tabs.config.js, packages/heartwood-components/components/07-navigation/01-tabs/tabs.hbs, packages/heartwood-components/components/07-navigation/tabs.scss, packages/react-heartwood-components/src/components/Card/components/OnboardingCard.js, packages/react-heartwood-components/src/components/Tabs/Tabs-story.js, packages/react-heartwood-components/src/components/Tabs/Tabs.js
[SBL-1599](https://sprucelabsai.atlassian.net/browse/SBL-1599)
This makes any instance of Tabs automatically truncate itself. A couple of notes:
- To avoid this behavior (as needed for Onboarding Cards) you can pass `isTruncatable={false}`
- The window resize event is debounced by 500ms for performance. We could make this faster if it seems too slow.
- If the active tab would be hidden, it will instead be shown first, with the rest of the tabs in the order in which they were authored. The active tab will never appear in the context menu.
- The Tabs component uses state in an atypical fashion; namely that `tabWidths` and `contextTabWidth` are sort of permanent. These values are captured in the initial render so that we can easily reason about when to hide and show which tabs on window …
=> Tabs — Ability to Truncate

packages/heartwood-components/components/99-web/sidebar.scss
[SBL-1604](https://sprucelabsai.atlassian.net/browse/SBL-1604)
Update styles so that icons are stroke-only by default. This can be overridden with the `.sidebar-item__icon--fill` class. 
- [x ] Feature
=> Sidebar icons styling

packages/spruce-utils/package.json
This missing peer dep breaks downstream projects; I shouldn't have to install it in ai-spruce-web so installing it as a dep of spruce-utils.
```
warning "@sprucelabs/spruce-utils > apollo-link-ws@1.0.12" has unmet peer dependency "subscriptions-transport-ws@^0.9.0".
```
```
ERROR  Failed to compile with 1 errors                                     12:53:19 PM
This dependency was not found:
* subscriptions-transport-ws in ./node_modules/apollo-link-ws/lib/webSocketLink.js
To install it, you can run: npm install --save subscriptions-transport-ws
```
=> fix(graphql): Include websocket dependency

package.json, packages/eslint-plugin-spruce/index.js, packages/eslint-plugin-spruce/package.json
- Adding this to aid in GQL rules enforcement; easier to apply a rule and get all the errors in the project than manually looking around for them. Plus it future-proofs the code.
- Going forward I'd much prefer to set a standard, write a linter rule to enforce it, then hand-off to one/many engineers to implement.
- This is a medium issue right now where we have several branches with mixed standards in ai-spruce-web; It's hard to refactor when new code might come in and break the new rules. Having a linter makes  this easy, I just tell everyone to merge up dev and they'll have the new parameters flagged in their IDEs (or otherwise they'll see them on CircleCI when they open a PR).
- I can move it somewhere else if we don't want it in workspace, but I dig the deploy process here and all …
=> feat(eslint): Add spruce eslint plugin

.circleci/config.yml
I've mentioned this previously, but `awscli` from `apt` is an old version that in my experience hasn't been very solid. At my last job I switched to using the recommended installation method (pip) as documented here: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html#install-tool-pip
I suspect that we've hit a certain s3 sync payload-size that is crashing the older cli, similar to this issue: https://github.com/aws/aws-cli/issues/1775
From memory, I think this also triggers when you pass a certain # of files.
This has little downside other than  `python:3-node` doesn't let us specify the node version. Currently it uses v10, but they could upgrade that to v12 later on this year, etc. At that stage we should write our own dockerfile  to gain more control here: …
=> Switch to using the latest awscli from pip

packages/spruce-skill/config/default.js
Currently deploying in non-local environments will crash skills.
This changes which directory to run from based on `process.env.ENV`. If in a non-local environment we run from the `build/` directory which has had flowtypes stripped.
=> Fix running skills in non-local environments

packages/spruce-utils/.babelrc
See https://github.com/zeit/next.js/blob/canary/packages/next/build/babel/preset.ts#L52-L56
I need to create a default config that all babel projects can use that has next's feature-set w/o the next-only junk. This was breaking utils with NODE_ENV=production. See the highlight in the link above.
=> fix(babel): utils: force auto modules

packages/heartwood-components/components/08-lists/02-text-list/text-list.config.js, packages/heartwood-components/components/08-lists/__list-partials/list-item.hbs, packages/heartwood-components/components/08-lists/lists.scss, packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.js, packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectList-story.js, packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
In the screenshot below, we now have the concept of list items with a disabled state, as well as an additional field below subtitle. I called this "note" given the context it was used in, but if y'all have a better name shout.
This creates the two new props on ListItem and implements them in the RecordSelectionList example.
**Merge after #388**
=> feat(RecordSelectionList): Allow for "unselectable" records

packages/heartwood-components/components/01-button/button.scss, packages/heartwood-components/components/08-lists/lists.scss, packages/react-heartwood-components/src/components/Icon/Icon.js, packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectList-story.js, packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
RecordSelectionList, with proper form controls
**Notes:**
- There is no canonical filled circle remove icon, so I'm using the lined version until one is available
- There is no "greyscale" Button with a hover/focus treatment (you can provide something busted to `kind` but that seems like a bug, and it doesn't have hover), so I'm using the default simple button.
- I chose to center align the select control / record item / remove button; the user may provide arbitrary components as the record renderer, and fixing top-alignment to be juuuuust right for `ListItem` felt like it would cause issues with non-ListItem recordRenderers.
=> task(RecordSelectionList): Finish styles with correct UI controls

packages/heartwood-components/components/06-modal/modal.scss, packages/react-heartwood-components/src/components/Modal/Modal.js, packages/spruce-skill/interface/pages/skill-views/example_skill_view_dialog.js, packages/spruce-utils/lib/iframes.js
- Added the concept of a "fullHeight" modal, which stretches to fill the screen. This is needed since we don't know the height of the iframe content ahead of time, and doing a bunch of resize work would be jank. We could fix the height to a smaller static value if this seems like overkill.
- Removed the CardBuilder from example skill view, since they didn't hold any meaningful data and were broken anyway with the recent cardbuilder changes.
- in `Iframes`, added an argument to the callbacks to reveal the original event, should you need it (I need it in core to determine which iframe is sending messages when I have multiples)
=> feat(spruce-skill): Support Skill View Dialogs in Core

packages/heartwood-components/components/__partials/icon.hbs, packages/heartwood-components/components/empty-state/empty-state.config.js, packages/heartwood-components/components/empty-state/empty-state.hbs, packages/heartwood-components/components/empty-state/empty-state.scss, packages/heartwood-components/stylesheets/heartwood-components.scss, packages/react-heartwood-components/src/components/EmptyState/EmptyState-story.js, packages/react-heartwood-components/src/components/EmptyState/EmptyState.js
Creates a re-usable React Empty State Heartwood Component with headline, subheadline, primary icon, and button action (w/ support for button kind [primary|secondary|caution|simple]) as well as a button icon).
* [SBL-1982](https://sprucelabsai.atlassian.net/browse/SBL-1982)
Screenshot review then code review.
Dependent on PR #393 getting merged first
No
=> [SBL-1982] Empty State React Component

packages/spruce-next-helpers/src/skillskit/next/_document.js, packages/spruce-skill/interface/next.config.js
- Props don't get passed on to error pages (since Next caught an exception / might not have the props and has to react predictably), so the injected props from skillView HOCs aren't available. This was removing the config necessary to inject stylesheets on error pages.
- Using the NextJS standard way of injecting universal config (`next/config`)
- We need to do this more generally in skillView / as a part of removing more of the prop injection
Closes [SBL-1387](https://sprucelabsai.atlassian.net/browse/SBL-1387)
=> fix(skill-view): Get _document config from next/config rather than props

packages/react-heartwood-components/src/components/Table/Table.js
Injects a default, user-friendly `EmptyState` component into the core of the `RecordTable` component that replaces the "No rows found" error message. When no data is loaded from the API, the Empty State component will be rendered in place of rows of data (see screenshot).
* [SBL-1996](https://sprucelabsai.atlassian.net/browse/SBL-1996)
Code review, local testing
n/a
No
=> Empty State defaults for RecordTable [SBL-1996]

packages/react-heartwood-components/src/components/BigCalendar/BigCalendar-story.js
Cleans out the only instance(s) of `alert()` in the react-heartwood-components codebase, which were found in `BigCalendar-story`. This is purely a clean-up PR and provides no real value for the BigCalendar component. I wouldn't be fine with closing this PR and simply removing the `alert`s. Let me know your thoughts.
[SBL-1985](https://sprucelabsai.atlassian.net/browse/SBL-1985)
Code review
n/a
No
=> refactor(BigCalendar-story): Uses the Toast component instead of alert

packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectList-story.js, packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
- Resulting from the relay migration
- You can use this to create UIDs on your own if your data didn't come 
with IDs!
=> feat(RecordSelectionList): Support arbitrary data with getRecordId

packages/react-heartwood-components/src/components/RecordTable/RecordTable.js
Allows button customization for the Empty State actions based on design requirements for Location Groups. Also addresses missing props in `RecordTableProps` from previous changes.
=> minor(RecordTable): Support for custom button kinds and icons

packages/heartwood-components/components/09-bigcalendar/bigcalendar.scss, packages/react-heartwood-components/src/components/BigCalendar/BigCalendar-story.js, packages/react-heartwood-components/src/components/BigCalendar/BigCalendar.js, packages/react-heartwood-components/src/components/BigCalendar/components/Views/Day.js, packages/react-heartwood-components/src/components/BigCalendar/utils/size.js
- This removes the JS-based sizing for calendar; using flexbox instead, 
and having BigCalendar take up the available space of its parent.
[SBL-2216](https://sprucelabsai.atlassian.net/browse/SBL-2216)
=> fix(BigCalendar): Prep for usage in core web [SBL-2216]

packages/spruce-skill-server/middleware/auth.js
* Fixes issue w/ running server tests where the connection is not secure
=> Set cookie w/ secure=false flag when TESTING flag is set

packages/spruce-skill-server/index.js, packages/spruce-skill/server/tests/ExampleEventTests.js, packages/spruce-skill/server/tests/lib/jwt.js
Ability to sign a custom `payload` when generating skill JWTs in tests. This gives us the ability to simulate and test event handlers in our server side tests.
* Fix issue where mock adapter was initialized after skill settings sync
* Update `generateSkillJWT` to accept payload
* Update `generateSkillJWT` to not require a user
* Implement example test for `get-views` event
=> Generate skill jwt w/ data for testing events

packages/heartwood-components/components/03-structure/page.scss, packages/heartwood-components/components/99-web/header-primary.scss, packages/heartwood-components/components/99-web/main-content.scss, packages/heartwood-components/components/99-web/sidebar.scss, packages/heartwood-components/components/feed/feed.scss
- More to do here, but this is mainly to just unblock right-rail in core 
calendar.
- Mostly I'm getting rid of anything that isn't flex (i.e. all these calcs that hard-ref the height of the header)
=> fix(view): Remove more non-flex references

packages/heartwood-components/components/03-structure/page.scss, packages/heartwood-components/components/99-web/main-content.scss, packages/heartwood-components/components/99-web/sidebar.scss, packages/react-heartwood-components/src/components/Core/components/Sidebar/components/SidebarSection/SidebarSection.js, packages/react-heartwood-components/src/components/Page/Page.js, packages/react-heartwood-components/src/components/View/View.js
- Also fixing zIndex for view/page so that page content can't overlap the sidebars on mobile.
=> feat(sidebar): Add mobile-only prop for sidebar sections

packages/heartwood-components/components/01-button/button.scss, packages/heartwood-components/components/02-forms/autosuggest.scss, packages/heartwood-components/components/05-feedback/toast.scss, packages/react-heartwood-components/src/components/Button/Button-story.js, packages/react-heartwood-components/src/components/Forms/components/Autosuggest/Autosuggest.js, packages/react-heartwood-components/src/components/Modal/Modal-story.js
[SBL-2067](https://sprucelabsai.atlassian.net/browse/SBL-2067) - Buttons: If "kind" is omitted, the grey default button has no hover/focus state
[SBL-2033](https://sprucelabsai.atlassian.net/browse/SBL-2033) - Toast - formatting for headline only is off
[SBL-1927](https://sprucelabsai.atlassian.net/browse/SBL-1927) - Autosuggest does not display properly in modals
Fixes the issues above. See below for Autosuggest in modal fix:
=> React Heartwood Component Updates

packages/spruce-node/mock/index.js, packages/spruce-skill-server/index.js, packages/spruce-skill-server/tests/v1APIMocks.js, packages/spruce-skill/.vscode/launch.json, packages/spruce-skill/package.json
* Add ability to mock / intercept v1 api calls
* Intercepts the `ctx.sb.user` event during tests and properly fetches data from the mock DB which allows us to run tests locally against `/api/1.0/<role>` endpoints and simulate v1 events
* Fixes issue where incorrect env var (should be `DB_MIGRATIONS` instead of `DISABLE_MIGRATIONS`) was being set during tests
=> Skills API v1 mocks / auth support for tests

packages/spruce-skill-server/tests/SpruceTest.js, packages/spruce-skill/server/tests/ExampleTests.js, packages/spruce-skill/server/tests/mocks/ExampleMock.js
* Passes the `SandboxMock` data into a skill's custom mocks so they can build data off the generated location, org, users, etc.
=> Pass core SandboxMock to custom mocks

packages/spruce-skill-server/tests/v1APIMocks.js
Hijacks the `ctx.sb.location()` call in tests and returns the proper location. Without this update `event.Location` is an empty object in events.
=> v1 event mock should fetch location

packages/spruce-skill-server/tests/SpruceTest.js, packages/spruce-skill-server/tests/lib/jwt.js, packages/spruce-skill-server/tests/v1APIMocks.js, packages/spruce-skill/server/tests/ExampleEmitTest.js
* Fix `generateSkillJWT` not attaching `organizationId` on location emit (like it does in real api emits)
* Implement `beforeEach` and `afterEach` methods in base test class
* Reset `global.testEmitResponse` before each test
* Add ability to trigger a callback on events. This will let us test `did-` events.  See [emitCallback](https://github.com/sprucelabsai/workspace.sprucebot-skills-kit/compare/canary...prerelease/test-enhancements#diff-541b623d3be5671c6ed47a58295138b1R89) in this PR for an example
=> Ability to test event emit callbacks

packages/react-heartwood-components/src/components/RecordTable/RecordTable.js, packages/react-heartwood-components/src/components/Table/Table.js
- Call `rowIsDirty` method for determining row dirtiness (wasn't actually being called before)
- Also adding a callback for navigation w/ pagination, which is needed if you want to have controlled row expansion. (This may make sense at the top-level table)
- Also controlling subcomponent expansion in RecordTable, which a downstream project could decide to override if they wanted.
=> Table fixes to support ESM Booking Tiers

packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
- Since RSL maintains its own state for the sake of infinite scrolling, needed a method to reset the state.
=> feat(RecordSelectionList): Add reset method

packages/react-heartwood-components/src/components/Page/components/PageHeader/PageHeader.js
- Default to Link
- In Skills this doesn't work directly, which I believe is related to 
https://github.com/zeit/next.js/issues/5598 ... so I expect this to work 
in Next v8, but that's not an easy lift.
- This is backwards-compatible, and mostly just a quick fix to get this 
working correctly in skills.
=> feat(PageHeader): Allow passing of backlink component

packages/spruce-skill-server/.gitignore, packages/spruce-skill-server/middleware/events.js, packages/spruce-skill-server/package.json, packages/spruce-skill-server/services/acl.js, packages/spruce-skill-server/tests/ACLTests.js, packages/spruce-skill-server/tests/SpruceTest.js, packages/spruce-skill-server/tests/apiMocks.js, packages/spruce-skill/config/default.js, packages/spruce-skill/package.json
* Adds strict ACL checks to the `ctx.services.acl. userIsAuthorizedForAcls()` method
* Now assumes the user is *not* authorized and verifies that every ACL requested is valid
* Now Throws errors on missing required parameters
* Adds check to API mock GQL server that the permission being checked is for the skill currently being tested
* Additional debug logging around ACLs and event contracts
* Removes (unused) jest and implements tests via mocha for `spruce-skill-server`
* Add tests around ACL check scenarios
* Update `package.json` scripts for tests to create the `tmp/` directory if it doesn't already exist
* Adds `this.ctx` to base test class for convenience
- [SDEV3-852](https://sprucelabsai.atlassian.net/browse/SDEV3-852)
=> Strict ACL checks & spruce-skill-server tests

packages/react-heartwood-components/package.json, packages/spruce-next-helpers/package.json, packages/spruce-next-helpers/src/skillskit/next/PageWrapper.js, yarn.lock
- As written, this can't actually set the token client-side, since a 
client cookie can't overwrite a server cookie.
- Also, the client cookie wasn't setting a path, resulting in duplicated 
cookies that broke auth in skills.
- Since it doesn't actually do anything and server-cookies covers our 
needs, removing it entirely.
- This was the only place the library was actually used in workspace, so 
removing the dependency
=> fix(Auth): Remove client-side cookie setting for JWT token

packages/eslint-config-spruce/index.js, packages/eslint-config-spruce/package.json, yarn.lock
* Change `singleLine` rule of `@typescript-eslint/member-delimiter-style` to `semi`
* VSCode w/ prettier isn't respecting rule with `comma` and causes it to thrash back and forth between a comma and semicolon on save/format
* Upgrade `@typescript-eslint/eslint-plugin`
=> Adjust TS ESLint rule

packages/heartwood-components/components/07-navigation/tabs.scss, packages/heartwood-components/stylesheets/base/_base.scss, packages/react-heartwood-components/src/components/Avatar/Avatar.tsx, packages/react-heartwood-components/src/components/ImageSSR/ImageSSR.js, packages/react-heartwood-components/src/index.js
* Removes hover state from tab buttons. This was a side-effect of adding a default hover state to the button component.
* Adds ImageSSR component to handle broken image urls. NOTE: This component is a workaround that fixes a known issue where the JSX `img` component does not handle `onError` events correctly.
* Update Avatar component to use new ImageSSR component to hide broken avatar urls.
=> [SDEV3-319] create new ImageSSR component to handle image load errors

packages/heartwood-components/components/09-bigcalendar/bigcalendar.scss, packages/react-heartwood-components/src/components/BigCalendar/BigCalendar-story.js, packages/react-heartwood-components/src/components/BigCalendar/BigCalendar.js, packages/react-heartwood-components/src/components/BigCalendar/components/Views/Day.js, packages/react-heartwood-components/src/components/BigCalendar/utils/size.js
* Reverts changes to BigCalendar that were made in preparation for new web that were breaking calendar scrolling in legacy booking. NOTE: Since BigCalendar is now in new web this change should not impact new web calendar.
- [SDEV3-1333](https://sprucelabsai.atlassian.net/browse/SDEV3-1333)
- [SDEV3-1327](https://sprucelabsai.atlassian.net/browse/SDEV3-1327)
* Need to update `react-heartwood-components` package in booking
=> [SDEV3-1333] [SDEV3-1327] calendar scroll

packages/spruce-node/index.js, packages/spruce-skill-server/tests/MessageTests.js, packages/spruce-skill-server/tests/v1APIMocks.js
* Sets the message `type` when creating messages
* Adds `requestOptions` to the mock api response for tests so that we can validate the parameters that are getting passed through on helper methods. In this scenario since we call `ctx.sb.message(...)` which then calls (and returns) `ctx.sb.post(...)` this will let us write basic tests around our helper methods to ensure that the proper parameters are getting sent to the API
- [SDEV3-794](https://sprucelabsai.atlassian.net/browse/SDEV3-794)
=> Pass message type when creating messages and add tests (SDEV3-794)

packages/spruce-node/https/index.js, packages/spruce-node/index.js, packages/spruce-skill-server/tests/GQLMethodTests.js
* Fixes issue where the query was being incorrectly sent from the helper method.  It's now been simplified to re-use the `https adapter "query" method` since mutations/queries follow the same request format for GQL
* Add tests for `ctx.sb.query` and `ctx.sb.mutation` helper methods
- [SDEV3-1353](https://sprucelabsai.atlassian.net/browse/SDEV3-1353)
=> Fix ctx.sb.mutation not properly calling api SDEV3-1353

packages/spruce-next-helpers/src/skillskit/index.js
- This is necessary to allow core to see if a Skill is running. Usually we just listen to the iframe's load event, but in some cases that happens before the core app has a chance to mount.
- [SDEV3-587](https://sprucelabsai.atlassian.net/browse/SDEV3-587)
=> feat(SpruceSkill): Add status check listener for core to ping [SDEV3-587]

packages/heartwood-components/components/01-button/button.scss
- [SDEV3-1032](https://sprucelabsai.atlassian.net/browse/SDEV3-1032)
- Skills/Web will need to be updated to the latest version of `react-heartwood-components`
**MAKE YOUR ICONS GO FROM THIS...**
**TO THIS!**
=> fix: [SDEV3-1032] fix broken icon styles on buttons

packages/react-heartwood-components/src/components/Forms/Forms-story.js, packages/react-heartwood-components/src/components/Forms/components/Select/Select.js
- The previous version threw errors, since React doesn't like the 
`selected` attribute.
- This provides an automatic default for uncontrolled Selects, and a 
requirement for how to handle defaults on controlled Selects.
- Added a note in storybook
=> fix(Select): Create defaults around placeholder option

packages/spruce-skill-server/tests/SpruceTest.js, packages/spruce-skill-server/tests/mocks/SandboxMock.js
This will allow for more diverse tests during skills development and testing.
- [SDEV3-1534](https://sprucelabsai.atlassian.net/browse/SDEV3-1534)
=> [SDEV3-1534] SDK is now exposing multiple orgs on the sandbox data

packages/heartwood-components/components/03-structure/card.scss, packages/react-heartwood-components/src/components/Card/components/CardBody.js
Adds ability to show line separators between card sections
- [SDEV3-581](https://sprucelabsai.atlassian.net/browse/SDEV3-581)
Need to update react-heartwood-component package version in skills
=> feat(Card): Add section separators

packages/react-heartwood-components/src/components/BigCalendar/components/EventDetails/components/EventDetailsFooter/EventDetailsFooter.js
* Adds `secondaryCTA` to the `BigCalendar` event details footer
- [SDEV3-503](https://sprucelabsai.atlassian.net/browse/SDEV3-503)
=> [SDEV3-503] Add "secondaryCTA" option to BigCalendar EventDetails footer

packages/spruce-skill-server/tests/v1APIMocks.js
* Fixes issue where an object instead of an empty array is returned by default (when `global.testEmitResponse` is not set) in tests
* Adds additional parameters `path` and `method` to emit callback in case we ever need to do additional checking of the underlying call that is made
- [SDEV3-1575](https://sprucelabsai.atlassian.net/browse/SDEV3-1575)
=> [SDEV3-1575] API mocks default response for emits should be an empty array

packages/spruce-next-helpers/src/skillskit/index.js, packages/spruce-skill/interface/pages/skill-views/dashboard_location/index.js, packages/spruce-skill/interface/pages/skill-views/example_skill_view_dialog.js
* Implements the ability to pass data back to parent iframe via modal `close` method. This is useful for things like parent iframe redirects or updating data after the modal is closed.
- [SDEV3-604](https://sprucelabsai.atlassian.net/browse/SDEV3-604)
Need to merge https://github.com/sprucelabsai/ai-spruce-web/pull/224
=> [SDEV3-604] Allow data to be passed on modal close

packages/heartwood-components/components/08-lists/lists.scss, packages/react-heartwood-components/src/components/List/List-story.js, packages/react-heartwood-components/src/components/List/List.js, packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.js
Gives `ListItem` components the ability to be selectable either as checkboxes or radios. This also renders the list item text as `<label>`s so that clicking them toggles the checkbox or selects the radio option.
Adds the following props to `List` and `ListItem` respectively:
- `selectableType`: either 'checkbox' or 'radio'
- `checkboxId`
- `checkboxProps`
- [SDEV3-1590](https://sprucelabsai.atlassian.net/browse/SDEV3-1590)
No
=> [SDEV3-1590] Heartwood List Item: Entire Row Should be Clickable

packages/heartwood-components/components/05-feedback/toast.scss
Makes the followup text (e.g. "Undo") visible in toasts.
- [x ] Bug
- [SDEV3-1628](https://sprucelabsai.atlassian.net/browse/SDEV3-1628)
Nope
=> [SDEV3-1628] followupText not visible on neutral toast

packages/spruce-skill-server/middleware/auth.js
* Fixes issue where the event handler for v2 events wasn't actually getting called
* This is due to the previous PR's (https://github.com/sprucelabsai/workspace.sprucebot-skills-kit/pull/503) optimization to break apart v1 and v2 handlers
- [SDEV3-1449](https://sprucelabsai.atlassian.net/browse/SDEV3-1449)
=> [SDEV3-1449] Fix event handler not getting called properly

packages/heartwood-components/components/02-forms/datepicker.scss
Style fixes to `DatePicker` that keep a "tail" on today's cell when it's selected as the start of a range.
- [SDEV3-1631](https://sprucelabsai.atlassian.net/browse/SDEV3-1631)
No
=> [SDEV3-1631] React Heartwood: Date Range Picker start date should have a "tail"

packages/heartwood-components/components/08-lists/lists.scss, packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectList-story.js, packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.js
Makes the `RecordSelectionList` use `ListItem`s consistently. Previously, it was using a hacky workaround because the `ListItem` didn't support select-ability. Now that it does, this ensures that the right component is in place.
None logged yet
- [SDEV3-1716](https://sprucelabsai.atlassian.net/browse/SDEV3-1716)
No, but it does deprecate the `renderRecord` prop and replaces it with `recordKeys` that tell `RecordSelectionList` how to map data into the `ListItem`s. This should ease dev effort as it will no longer be required to write out the render method for list items and instead you can just pass in the relevant keys.
This will also require a re-implementation effort eventually. I didn't remove the `renderRecord` prop, but without `recordKeys`, it won't render properly.
=> [SDEV3-1716] Prerelease/record selection list

packages/heartwood-components/components/01-button/context-menu.scss, packages/react-heartwood-components/src/components/ContextMenu/ContextMenu-story.js, packages/react-heartwood-components/src/components/ContextMenu/ContextMenu.js
Updates the `ContextMenu` component to use a [portal](https://reactjs.org/docs/portals.html) so that it won't be clipped when its parent has `overflow: hidden;`. This also required the addition of a resize handler to handle positioning. In addition, this deprecates `isLeftAligned`, `isRightAligned`, and `isBottomAligned` in favor of letting the component make its own layout decisions, rather than relying on a best guess. These props could be reintroduced if we deem them necessary.
- [SDEV3-1717](https://sprucelabsai.atlassian.net/browse/SDEV3-1717)
Every `ContextMenu` instance will need to be updated.
=> [SDEV3-1717] Context Menu - avoid clipping

packages/heartwood-components/components/02-forms/autosuggest.scss, packages/react-heartwood-components/src/components/Forms/Forms-story.js, packages/react-heartwood-components/src/components/Forms/components/Autosuggest/Autosuggest.js
Enables `Autosuggest` to use a [portal](https://reactjs.org/docs/portals.html) so that suggestions will not be clipped. Also, adds styling for the selected (via keyboard arrows) item. Verifiable in Storybook under Forms > Autosuggest.
- [SDEV3-1718](https://sprucelabsai.atlassian.net/browse/SDEV3-1718)
No, but it does block [SDEV3-1663](https://sprucelabsai.atlassian.net/browse/SDEV3-1663).
=> [SDEV3-1718] Autosuggest should not push input up or clip suggestions

packages/heartwood-components/components/01-button/context-menu.scss, packages/heartwood-components/components/02-forms/autosuggest.scss
Fixes context menu and autosuggest z-index so they show up above modals and other portal-ly components
NOTE: This doesn't need to be deployed to fix the issue as it's a redundant fix that is self-contained in booking at the moment, but could be present in future heartwood implementations.
- [SDEV3-1745](https://sprucelabsai.atlassian.net/browse/SDEV3-1745)
=> fix: [SDEV3-1745] context and auto suggests z-index

packages/spruce-skill-server/middleware/events.js
* Fixes bug where skills w/ `EVENT_VERSION=1` was not logging or passing through the `eventId` or `retryId` 
- [SDEV3-940](https://sprucelabsai.atlassian.net/browse/SDEV3-940)
=> [SDEV3-940] Fix EVENT_VERSION=1 eventId and retryId not passed through on ctx.event

packages/react-heartwood-components/src/components/Page/Page-story.js, packages/react-heartwood-components/src/components/Page/components/PageHeader/PageHeader.js
- In core I'll need this to prevent jank when switching between skill 
view iframes with/without headers
- Cleanup, alphabetize long list of props
=> fix(PageHeader): Allow setting of additional classnames

packages/heartwood-components/components/07-navigation/tabs.scss, packages/react-heartwood-components/.storybook/StylesProvider.js, packages/react-heartwood-components/.storybook/Wrapper.js, packages/react-heartwood-components/src/stylesheets/global.sass
- Visual parity with anchor tabs, as we have on core
- flex: 0 on first tab to make flush with title
- Disable min-width on .btn
- Also remove redundant global.sass includes (duplicated the direct include of heartwood styles)
- [] Feature
In Core, with anchors:
In canary, buttons in tabs have inconsistent / non-aligned spacing:
Fixed in this PR, buttons consistent with anchor tabs:
=> fix(Tabs): Correct styles for buttons in tabs

packages/heartwood-components/components/03-structure/page.scss, packages/react-heartwood-components/src/components/Page/Page-story.js, packages/react-heartwood-components/src/components/Page/components/PageHeader/PageHeader.js
- This is a controlled attribute; downstream users are responsible for 
triggering it.
- In core we use it for skillview pages that may/may not have headers -- 
transitioning between them
- Also fixup the bottom-border attribute
(Smoother IRL than in GIF 😂)
=> feat(PageHeader): Add collapsibility for PageHeader

packages/spruce-skill/.circleci/config.yml, packages/spruce-skill/package.json, yarn.lock
* Upgrades to beta release of `semantic-release` to get prerelease support
* Uses new config: https://github.com/sprucelabsai/sprucelabs-semantic-release/blob/master/index.js
Example: https://github.com/sprucelabsai/spruce-release-testing/releases
* On merge to `dev`, `qa`, and `alpha` a git tag will be created: `<version>.<env>.<build number>@<env>`
* The package.json will NOT be updated
* The changelog will NOT be updated
* A github "release" for the tag will be created with the changelog information
* On merge to `master` a git tag will be created: `<version>`
* The package.json will be updated
* The changelog will be updated
* A github "release" for the tag will be created with the changelog information
- [SDEV3-1441](https://sprucelabsai.atlassian.net/browse/SDEV3-1441)
=> [SDEV3-1441] Upgrade semantic release for new versioning strategy

packages/spruce-next-helpers/src/skillskit/index.js, packages/spruce-next-helpers/src/skillskit/next/PageWrapper.js
This adds the ability to force-authenticate Safari if no cookies have ever been set for that skill, as was done in legacy web. See https://gist.github.com/iansltx/18caf551baaa60b79206 for an overview of the issue.
- Allow redirect if JWTv2 is supplied
- Allow spruce.ai backlinks from skill redirects
- [SDEV3-1945](https://sprucelabsai.atlassian.net/browse/SDEV3-1945)
=> feat(Skillskit): Restore the concept of forced auth for the safari case [SDEV3-1945]

packages/spruce-next-helpers/src/skillskit/next/PageWrapper.js
Fixes issue where loading a v2 skill in legacy web and then navigating to that skill in heartwood web would cause errors until cookies were cleared.
This _could_ also fix other authentication issues we've seen. Previously, if the jwt was set in the cookie it would use that over the query string which is wrong because the one in cookies might have expired.
* Prioritize JWTs in the query string over what's in cookies
* If jwt is found in query string, set it in cookies
* For authentication purposes prefer `jwtV2` over `jwt`
- [SDEV3-1889](https://sprucelabsai.atlassian.net/browse/SDEV3-1889)
=> [SDEV3-1889] Fix double JWT authentication issues

packages/react-heartwood-components/package.json
- If you don't clean the `lib` folder, `tsc` has issues with overriding the previous definition files.
=> fix(build): Run clean before build

packages/react-heartwood-components/src/components/RecordTable/RecordTable-story.tsx, packages/react-heartwood-components/src/components/RecordTable/RecordTable.tsx
- Ensures proper "clear filter" state if zero records are returned
- [SDEV3-2018](https://sprucelabsai.atlassian.net/browse/SDEV3-2018)
=> fix(RecordTable): Correct usage of getNoDataProps [SDEV3-2018]

packages/heartwood-components/components/03-structure/card.scss, packages/react-heartwood-components/src/components/Card/Card-story.js, packages/react-heartwood-components/src/components/Card/components/CardBuilder.js
- Needed for redesigned card in Update Group page
- Not 100% matched to comps for padding, font sizes, etc., but I believe Cards generally are off-spec now and need a design pass from Jeremy; trying to add the feature without variating too much from what is already there.
- [SDEV3-1921](https://sprucelabsai.atlassian.net/browse/SDEV3-1921)
From comps:
Implemented:
=> feat(Cards): Add concept of a footer action helper [SDEV3-1921]

packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectList-story.js, packages/react-heartwood-components/src/components/RecordSelectionList/RecordSelectionList.tsx
- Need a separate prop for the filtered empty state, since it needs the "show all" field, which taps into internal methods to clear the search.
- [SDEV3-2110](https://sprucelabsai.atlassian.net/browse/SDEV3-2110)
=> fix(RSList): Handle filtered EmptyState separately [SDEV3-2110]

packages/spruce-skill/package.json
Moves `graphql` to a dependency in `spruce-skill` and keeps it as a `peerDependency` in other skills kit packages
- [SDEV3-2060](https://sprucelabsai.atlassian.net/browse/SDEV3-2060)
=> [SDEV3-2060] Make "graphql" a dependency in spruce-skill

packages/react-heartwood-components/src/components/List/List.tsx
Hotfix, oversight in the types of List. Need before upgrading core, will merge once tests run.
=> Hotfix: types for ListWrapper

packages/react-heartwood-components/src/components/Forms/components/TextInput/TextInput.tsx
- Should be `ReactNode`, not DOM `Node`.
=> fix(TextInput): Correct type for helper

.circleci/config.yml
- Only need to update the cache for `test`, since that's a prerequisite 
for the others.
- This has been working fine for months in ai-web, and can hopefully 
speed up our builds in workspace as well.
=> fix(CI): Cache yarn packages

packages/react-heartwood-components/src/components/Core/components/FooterPrimary/components/Legal/Legal.js, packages/react-heartwood-components/src/components/Core/components/Sidebar/components/SidebarFooter/SidebarFooter.js
Takes the "help" button out of the main sidebar and updates the privacy policy and terms links to point to the right place when used in core.
I realize this should go much further, e.g. converting the components to TS, moving them into core, but didn't want to slow us down given timing.
=> fix: Sidebar links

packages/heartwood-components/components/02-forms/text-input.scss, packages/react-heartwood-components/src/components/Forms/Forms-story.js, packages/react-heartwood-components/src/components/Forms/components/Autosuggest/Autosuggest.tsx, packages/react-heartwood-components/src/components/Table/components/TableSearch/TableSearch.tsx
Enables the `Autosuggest` to have an icon that it renders in the input. By default, there is no icon. Also updates `TableSearch` to always show the search icon in its input.
- [SDEV3-2151](https://sprucelabsai.atlassian.net/browse/SDEV3-2151)
No
=> [SDEV3-2151] Autosuggest Icon

.vscode/settings.json
* Exclude `build/` directories from showing up in vscode file finder and search
N/A
=> DX - exclude build directories from vscode search/spotlight

packages/react-heartwood-components/src/components/Forms/components/Autosuggest/Autosuggest.tsx
- ProfileUserLocation in Core supplies a node to postLabel, so that we can have a click handler to show permissions / style it as a link
=> fix(AutoSuggest): Allow helper/postLabel to both accept a node or a string

packages/spruce-skill-server/tests/CoreStartupTests.js, packages/spruce-skill/server/services/cards.js, packages/spruce-skill/server/services/cards/dashboardUserCards.js
* Fixes card service not getting loaded
* Fix example data so it's valid and renders cards in HW web properly
- [SDEV3-2165](https://sprucelabsai.atlassian.net/browse/SDEV3-2165)
=> [SDEV3-2165] Workspace should return valid card data

packages/heartwood-components/components/03-structure/table.scss, packages/react-heartwood-components/src/components/RecordTable/RecordTable-story.tsx, packages/react-heartwood-components/src/components/RecordTable/RecordTable.tsx
- With a bit of latency, the table will flash the "no data" empty state if loading w/ no records. This happens if you add a filter that results in no records, then delete it.
- Added a latency simulator to the basic story to test this out.
- [SDEV3-2215](https://sprucelabsai.atlassian.net/browse/SDEV3-2215)
=> fix(RecordTable): Add loader when loading w/ no records [SDEV3-2215]

packages/spruce-utils/lib/errors.js, packages/spruce-utils/lib/graphql.js
SpruceWebError supports`friendlyReason` and graphql now sets it when available on the first error returned.
- [SDEV3-2280](https://sprucelabsai.atlassian.net/browse/SDEV3-2280)
NA
NA
NA
=> [SDEV3-2280] friendly Error

packages/heartwood-components/components/02-forms/checkbox.scss, packages/react-heartwood-components/src/components/Forms/components/Radio/Radio.js
Fixes issue where radio buttons are hidden by default because of styles applied to checkbox `indeterminate` state.
- [SDEV3-2306](https://sprucelabsai.atlassian.net/browse/SDEV3-2306)
=> [SDEV3-2306] fix: hidden radio buttons

packages/spruce-node/index.ts, packages/spruce-skill-server/package.json, packages/spruce-skill/package.json
Keeps backwards compatibility w/ API sync by sending `eventContract` and `acl` as stringified json
Accepting input as JSON is possible but breaks compatibility so we'll need to evaluate if/how we introduce that: https://github.com/sprucelabsai/com-sprucebot-api/pull/598
A union would have been ideal but unfortunately GQL doesn't yet support input union types: https://github.com/graphql/graphql-spec/issues/488
Also, fixes issue where `supertest` needs to be in `dependencies` and not `devDependencies`
=> [SDEV3-2361] Send eventContract and acl as stringified json

packages/react-heartwood-components/src/components/Text/Text-story.tsx, packages/react-heartwood-components/src/components/Text/Text.tsx
- Added a trivial example in the stories just to validate the issue. This was happening in ai-web after I upgraded; `href` wasn't in props so it was failing TSC checks there.
=> fix(Text): Update types to allow arbitrary HTML props

packages/spruce-skill-server/gql/helpers.ts, packages/spruce-skill-server/interfaces/ctx.ts, packages/spruce-skill/package.json
* Move GQL helper definition to helpers file and import the type for `ctx`
* Adds missing `enhancedResolver` gql helper definition
* Update `buildConnection` type to take optional `name`
=> [SDEV3-2361] Update gql helper types

packages/spruce-skill-server/config/default.ts, packages/spruce-skill-server/controllers/events.ts, packages/spruce-skill-server/factories/context.ts, packages/spruce-skill-server/gql/helpers.ts, packages/spruce-skill-server/gql/router.ts, packages/spruce-skill-server/interfaces/acls.ts, packages/spruce-skill-server/interfaces/config.ts, packages/spruce-skill-server/lib/GraphQLSubscription.ts, packages/spruce-skill-server/middleware/auth.ts, packages/spruce-skill-server/middleware/events.ts, packages/spruce-skill-server/models/User.ts, packages/spruce-skill-server/package.json, packages/spruce-skill-server/services/cache/Memory.ts, packages/spruce-skill-server/tests/ACLTests.ts, packages/spruce-skill-server/tests/EmitTests.ts, packages/spruce-skill-server/tests/mocks/SandboxMock.ts, packages/spruce-skill-server/tests/mocks/apiMocks.ts, packages/spruce-skill/bin/buildConfigs.js, packages/spruce-skill/interface/__mocks__/client.js, packages/spruce-skill/package.json, packages/spruce-skill/server/interfaces/config.ts, yarn.lock
* Switches to forked version of `node-config` module to fix issue w/ typescript compilation where on a production build `config` keys were nested under `config.default.default` and unable to be found, causing an authentication redirect loop
* https://github.com/sprucelabsai/node-config/pull/1/files
* Removes `config.get(...)` references in favor of strongly typed `config.KEY`
=> [SDEV-2361] Strong config types

packages/eslint-config-spruce/index.js
Update `@typescript-eslint/camelcase` rule to allow variables to be non-camelcase when they begin with `can_` or `skill_can_`
=> Update "@typescript-eslint/camelcase": Allow non-camel case for permissions

packages/spruce-skill/interface/next.config.js
Updates the `next.config.js` to extend the `resolve` config which fixes `.tsx` files not getting resolved properly
=> Fix .tsx imports not working without extension

package.json, packages/eslint-config-spruce/index.js, packages/eslint-config-spruce/package.json, packages/react-heartwood-components/package.json, packages/react-heartwood-components/src/components/Card/components/CardBuilder.tsx, packages/react-heartwood-components/src/components/EventDetails/eventDetailsMock.ts, packages/react-heartwood-components/src/components/Forms/components/Autosuggest/Autosuggest.tsx, packages/react-heartwood-components/src/components/Icon/Icon.tsx, packages/react-heartwood-components/src/components/Text/Text.tsx, packages/react-heartwood-components/src/components/Toast/Toast.tsx, packages/react-heartwood-components/src/components/Toast/components/ToastWrapper/ToastWrapper.tsx, packages/react-heartwood-components/src/custom-types.d.ts, packages/spruce-next-helpers/src/skillskit/index.ts, packages/spruce-node/index.ts, packages/spruce-node/package.json, packages/spruce-node/utilities/url.ts, packages/spruce-skill-server/gql/Schema.ts, packages/spruce-skill-server/gql/helpers.ts, packages/spruce-skill-server/index.ts, packages/spruce-skill-server/lib/GraphQLSubscriptionServer.ts, packages/spruce-skill-server/middleware/auth.ts, packages/spruce-skill-server/package.json, packages/spruce-skill-server/services/Acl.ts, packages/spruce-skill-server/tests/lib/SpruceTest.ts, packages/spruce-skill/package.json, packages/spruce-types/package.json, packages/spruce-types/src/generated/hw-gql.ts, packages/spruce-types/src/gql/CardBuilder.gql, yarn.lock
- Upgrades to TS 3.6.3, which necessitated an upgrade to our TS+eslint integration.
- Fixes mostly for `prefer-const`.
- Fix a few typing issues that 3.6.3 was able to flag that 3.4.x missed.
=> feat(Typescript): Upgrade to 3.6.3

packages/spruce-types/src/generated/hw-gql.ts, packages/spruce-types/src/gql/ActionExecuter.gql
Makes the skill view modal signature match other instances of loading skill view.
NA
NA
NA
NA
=> feat: skill modal match other interfaces

packages/spruce-skill-server/tests/lib/SpruceTest.ts, sprucebot-skill-kit.code-workspace
Fixes a reference to the right version of typescript when working in the Workspace. Also, types `triggerEvent`
- [SDEV3-2185](https://sprucelabsai.atlassian.net/browse/SDEV3-2185)
NA
NA
NA
=> [SDEV3-2185] fixed ts library reference, triggerEvent types

packages/spruce-skill/.vscode/settings.json
* Fix vscode config so only eslint fix formatter runs
=> Prevent double save formatters

packages/spruce-skill/.vscode/settings.json
Excludes `build` directories from search / watch in vscode which should help performance and prevent us from accidentally editing a built file
=> VScode should exclude build/ directory from watch

packages/react-heartwood-components/src/components/Button/Button.tsx, packages/react-heartwood-components/src/components/ButtonGroup/ButtonGroup.tsx, packages/react-heartwood-components/src/components/ContextMenu/ContextMenu.tsx, packages/react-heartwood-components/src/components/EventDetails/EventDetails-story.tsx, packages/react-heartwood-components/src/components/EventDetails/EventDetails.tsx, packages/react-heartwood-components/src/components/EventDetails/components/EventDetailsItem/EventDetailsItem.tsx, packages/react-heartwood-components/src/components/EventDetails/eventDetailsMock.ts, packages/react-heartwood-components/src/components/Forms/components/Checkbox/Checkbox.tsx, packages/react-heartwood-components/src/components/Forms/components/Radio/Radio.tsx, packages/react-heartwood-components/src/components/List/List.tsx, packages/react-heartwood-components/src/components/List/components/ExpandableListItem/ExpandableListItem.tsx, packages/react-heartwood-components/src/components/List/components/ListItem/ListItem.tsx, packages/react-heartwood-components/src/components/SplitButton/SplitButton.tsx, packages/spruce-types/src/generated/hw-gql.ts, packages/spruce-types/src/gql/ActionExecutor.gql
- Applies action executors to EventDetails as specified in https://github.com/sprucelabsai/spruce-rfcs/tree/master/text/0000-action-executors
- Adds onComplete and onCancel actions to GQL for ActionExecutors
- Adds actions to all elements in EventDetails storybook (logs to console)
- [SDEV3-2355](https://sprucelabsai.atlassian.net/browse/SDEV3-2355)
=> feat(EventDetails): Add action executor arch to components [SDEV3-2355]

packages/react-heartwood-components/src/components/Button/Button.tsx, packages/react-heartwood-components/src/components/ButtonGroup/ButtonGroup.tsx, packages/react-heartwood-components/src/components/Card/components/CardBuilder.tsx, packages/react-heartwood-components/src/components/Card/components/CardHeader.tsx, packages/react-heartwood-components/src/components/Card/components/OnboardingCard.tsx, packages/react-heartwood-components/src/components/ContextMenu/ContextMenu.tsx, packages/react-heartwood-components/src/components/EventDetails/EventDetails.tsx, packages/react-heartwood-components/src/components/EventDetails/components/EventDetailsItem/EventDetailsItem.tsx, packages/react-heartwood-components/src/components/EventDetails/eventDetailsMock.ts, packages/react-heartwood-components/src/components/Image/Image.tsx, packages/react-heartwood-components/src/components/List/List.tsx, packages/react-heartwood-components/src/components/List/components/ListHeader/ListHeader.tsx, packages/react-heartwood-components/src/components/Toast/Toast-story.tsx, packages/react-heartwood-components/src/components/Toast/Toast.tsx, packages/react-heartwood-components/src/index.tsx, packages/spruce-types/src/generated/api-gql.ts, packages/spruce-types/src/generated/hw-gql.ts, packages/spruce-types/src/gql/CardBuilder.gql, packages/spruce-types/src/gql/List.gql, packages/spruce-types/src/gql/Toast.gql
Lets you use heartwood components manually and through gql endpoints without warnings/errors.
=> HW components can take both generated props and standard props

packages/spruce-types/src/generated/api-gql.ts, packages/spruce-types/src/generated/hw-gql.ts, packages/spruce-types/src/gql/types/ActionExecutor.gql
* Adds `locationId` and `organizationId` to `ActionEmitEventPayload`
* Regenerate gql types for API w/ action executor implementation
- [SDEV3-2607](https://sprucelabsai.atlassian.net/browse/SDEV3-2607)
=> [SDEV3-2607] Update GQL for ActionExecutor

.circleci/config.yml
Set up CI to only run build on merge to `canary` since test will have already passed on the branch we're merging
=> Only run build on canary branch

packages/spruce-skill-server/package.json, packages/spruce-types/package.json, yarn.lock
* Fix circular dependency where `@sprucelabs/spruce-skill-server` was required by `@sprucelabs/spruce-types` which can cause issues w/ builds
* Fixes issue w/ `spruce-types` prerelease referenced instead of linked/current version
=> Fix dependencies

packages/eslint-config-spruce/package.json, yarn.lock
* Fixes the annoying bug in vscode where new files weren't linted until reload
* Upgrades other eslint packages for good measure
=> Update eslint packages

packages/heartwood-components/components/99-web/sidebar.scss
Sidebars with the prop isLarge will now have a max-width of 360px rather than a hardcoded width of 360px.
- [SDEV3-2786](https://sprucelabsai.atlassian.net/browse/SDEV3-2786)
=> Add max width for large sidebar

packages/heartwood-components/components/03-structure/page.scss, packages/heartwood-components/components/99-web/sidebar.scss
There seems to be an issue with scrolling on position:fixed overlays in Safari and iOS. The background scrolls when the user attempts to scroll the sidebar. Here is a popular [SO thread](https://stackoverflow.com/questions/41594997/ios-10-safari-prevent-scrolling-behind-a-fixed-overlay-and-maintain-scroll-posi) on it.
There are a slew of workarounds for it, many include adding  javascript to components or using npm packages. I've found that changing the mobile sidebars from position:fixed to position:absolute resolves this issue in Safari (on desktop) and hopefully fixes the issue in iOS as well (need to test).
- [SDEV3-2756](https://sprucelabsai.atlassian.net/browse/SDEV3-2756)
=> Safari / iOS sidebar scroll issue

packages/spruce-node/index.ts
`linksToWebView` option not respected by `ctx.sb.message()`
- [SDEV3-2852](https://sprucelabsai.atlassian.net/browse/SDEV3-2852)
=> [SDEV3-2852] Fix linksToWebView option not getting passed through on ctx.sb.message

packages/heartwood-components/components/event-details/event-details.scss
Adds padding needed for event details to look right in RR.
=> padding on text in a card_section in eventdetails

packages/spruce-next-helpers/src/index.ts, packages/spruce-next-helpers/src/skillskit/index.ts, packages/spruce-types/src/gql/queries/UIEnhancements.ts
* Define `route` on `IModal` which accepts a `slug` for authentication purposes when loading a view in a modal
* Add missing fields to `getUIEnhancements` query
- [SDEV3-2814](https://sprucelabsai.atlassian.net/browse/SDEV3-2814)
=> [SDEV3-2814] IModal updates for authentication needs

packages/react-heartwood-components/src/components/ButtonGroup/ButtonGroup.tsx, packages/react-heartwood-components/src/components/SplitButton/SplitButton.tsx
- Add temp fix for passing `action` to button by cooercing it into an 
IHWAction; looking at a followup fix
- Took a quick look at fixing "actions" (meaning buttons in the old context) but that's not easy at all. Needs a deeper dive...
- [SDEV3-2927](https://sprucelabsai.atlassian.net/browse/SDEV3-2927)
=> fix(ButtonGroup): Handle actions and close dropdown [SDEV3-2927]

packages/react-heartwood-components/src/components/Toast/Toast.tsx, packages/spruce-types/src/generated/api-gql.ts, packages/spruce-types/src/generated/hw-gql.ts, packages/spruce-types/src/gql/types/Toast.gql
Gives toast a `removeAction` so we can do things when the dismiss button is hit.
NA
NA
NA
NA
=> Remove action for toast

packages/spruce-node/index.ts, packages/spruce-skill/server/gql/resolvers/Test/sdl.ts, packages/spruce-skill/server/interfaces/events-generated.ts, packages/spruce-skill/server/tests/ExampleGQLTests.ts
The `updateUser` mutation never actually worked as written. This updates that method, changing it to use the `updateGuest` mutation
- [SDEV3-2976](https://sprucelabsai.atlassian.net/browse/SDEV3-2976)
=> [SDEV3-2976] Fix updateUser mutation

packages/heartwood-components/components/06-modal/modal.scss
Default modal height to 100% on screens 500px or less
- [SDEV3-2767](https://sprucelabsai.atlassian.net/browse/SDEV3-2767)
=> [SDEV3-2767] Default modal height to 100% on screens 500px or less

packages/heartwood-components/components/99-web/header-primary.scss
Only show search placeholder text after md screen size breakpoint
Fixes issue in screenshot:
- [SDEV3-2798](https://sprucelabsai.atlassian.net/browse/SDEV3-2798)
=> [SDEV3-2798] Only show search placeholder text after md screen size breakpoint

packages/spruce-node/https/index.ts, packages/spruce-node/index.ts, packages/spruce-skill-server/tests/lib/HttpsMock.ts
Adds `spruce-node` method for updating a user profile image from a url
- [SDEV3-2849](https://sprucelabsai.atlassian.net/browse/SDEV3-2849)
=> [SDEV3-2849] Update user profile image from url

packages/react-sprucebot/src/components/DateSelect/DateSelect.js
Pass in prop to hide prev nav button
Looks like this is possible based off the source code here:
(https://github.com/airbnb/react-dates/blob/master/src/components/DayPickerSingleDateController.jsx)
- [SDEV3-3041](https://sprucelabsai.atlassian.net/browse/SDEV3-3041)
=> [SDEV3-3041] Add no nav prev button prop

Procfile, package.json
Fixes a build issue on Heroku.  This also sets the workspace node version to 10, the build has been failing since Heroku updated to node 12.  
Details on node 12 issue: The version of sqlite3 we are using (4.0.6) fails to compile in node 12. NaN package -  https://github.com/nodejs/nan/issues/849 -  this says the fix is included in 4.07 - https://github.com/mapbox/node-sqlite3/pull/1093
=> fix: Procfile path, force node to node 10

packages/react-heartwood-components/src/components/Button/Button.tsx, packages/react-heartwood-components/src/components/Card/Card-story.tsx, packages/react-heartwood-components/src/components/Card/components/CardBuilder.tsx, packages/react-heartwood-components/src/components/EventDetails/eventDetailsMock.ts, packages/spruce-types/src/generated/hw-gql.ts, packages/spruce-types/src/gql/types/Button.gql
- Formerly we tried omitting and overwriting props from spruce-types due to slight differences in the React vs. data-driven APIs.
- Since then we've upped our understanding of this type of extension, and it's less necessary. Most specifically I'm doing the correct union-type to allow extension of `children` onto CardBody, which was the big hold-up.
- It's important that builders do not modify our core types going forward, as we're using those as the source of truth. Variance here will lead to bugs, etc.
=> CardBuilder: Clean up types for better adherence to shared types

packages/react-sprucebot/src/skillskit/next/_document.js
v7 version of https://github.com/sprucelabsai/workspace.sprucebot-skills-kit/pull/825
=> feat(SkillsKit): Only allow whitelabel stylesheets on guest pages (v7) [SDEV3-3094]

packages/react-sprucebot/lib/skillskit/next/Page.js, packages/react-sprucebot/lib/skillskit/next/_document.js, packages/react-sprucebot/src/skillskit/next/Page.js, packages/react-sprucebot/src/skillskit/next/_document.js
- Makes it so that the `isHeartwood` query parameter controls 
whitelabeling
- Removes the previously-added concept of role controlling 
whitelabeling.
- [SDEV3-3094](https://sprucelabsai.atlassian.net/browse/SDEV3-3094)
=> fix(SkillsKit): Move whitelabelling from _document to Page mount

packages/spruce-next-helpers/src/skillskit/next/PageWrapper.js, packages/spruce-next-helpers/src/skillskit/next/_document.js
- Moves `orgWhitelabel` from _document to PageWrapper for v9 skills
=> fix(SkillsKit): Update to org whitelisting (v9)

packages/spruce-next-helpers/src/skillskit/next/PageWrapper.js
- This isn't necessary in V9, since all relevant views at that stage would be heartwood-only.
- In the case of a hybrid skill (v9 for most, but still legacy views) legacy views are covered by the v7 of react-sprucebot, which now instruments org whitelabels in the `Page` component.
=> fix(Whitelabel): Remove org whitelabel from v9

packages/react-heartwood-components/src/components/PageBuilder/PageBuilder-story.tsx, packages/react-heartwood-components/src/components/PageBuilder/PageBuilder.tsx, packages/spruce-types/src/generated/hw-gql.ts, packages/spruce-types/src/gql/types/PageBuilder.gql
☝️ demonstration of this PR, with two sections being pushed into the PageBuilder (a CardBuilder and a Button)
- This is a bare-bones layout for how we'll add items to PageBuilder 
with proper type-checking.
- I threw `Button` in there to demonstrate multiple types; it's not 
something we specifically talked about but adding a simple button 
section could be handy.
- The best way to think about this is as a data/component scaffold; once we add components that have multiple sections, i.e. `TwoColLayout`, each column could contain a `PageBuilder` of its own. Keeping this system basic should allow for infinite layout combinations once we have the proper components fueling it.
=> feat(PageBuilder): Create basic architecture
